// GENERATED by cmd/contractgen from the Go view types (docs/adr/0039-presentation-split.md).
// Do not edit: change the Go view, run `go run ./cmd/contractgen > api/views.gen.ts`.
//
// Every field is always present. A nil pointer, slice or map, and a zero time, are null.
// A duration is whole seconds, rounded up, under the field's name with `_seconds` appended.

export interface AchievementLine {
  achievement: Named
  count: number
  done: number
  reward: number
  earned: boolean
  cash: number
}

export interface AchievementView {
  achievement: Named
  cash: number
  withheld: number
}

export interface AchievementsView {
  lines: AchievementLine[] | null
}

export interface AllocationConfirmView {
  place: GovPlace
  lever: GovLever
  draft: string
  new: Record<string, number> | null
  vote_by: string
}

export interface AllocationEditView {
  place: GovPlace
  lever: GovLever
  draft: string
  lines: AllocationLine[] | null
  total: number
  spend_share_bps: number
  next_change_in_seconds: number
  changed: boolean
}

export interface AllocationLine {
  code: string
  share: number
  down: string
  up: string
}

export interface AmountOption {
  amount: number
  nonce: string
  all: boolean
}

export interface AppointDoneView {
  office: string
  place: GovPlace
  player: GovPlayer
  dismissed: boolean
  term_ends_in_seconds: number
}

export interface AppointRefusalView {
  kind: string
  gov: GovRefusal | null
  office: string
}

export interface AppointView {
  office: string
  place: GovPlace
  player: GovPlayer
}

export interface AuctionDetailView {
  line: AuctionLine
  min_next: number
  bids: number
  payment: PaymentChoice | null
  nonce: string
  seller: string
}

export interface AuctionLine {
  no: number
  item: Named
  quality: number
  high_bid: number
  reserve: number
  remaining_seconds: number
  ends_at: string | null
  status: string
  mine: boolean
  leading: boolean
}

export interface AuctionNewView {
  item: Named
  ref: string
  quality: number
  reserves: number[] | null
  durations: number[] | null
  nonce: string
}

export interface AuctionOpenedView {
  no: number
  item: Named
  reserve: number
  duration_seconds: number
  ends_at: string | null
}

export interface AuctionRefusalView {
  kind: string
  no: number
  min_next: number
  count: number
}

export interface AuctionView {
  kind: string
  no: number
  item: Named
  amount: number
  fee: number
}

export interface AuctionsView {
  city_code: string
  city: string
  auctions: AuctionLine[] | null
  at_house: boolean
  way: Way | null
  unavailable: Unavailable | null
}

export interface AvatarChoice {
  code: string
  name: string
  emoji: string
}

export interface AvatarRef {
  code: string
  emoji: string
  photo: boolean
}

export interface AvatarsView {
  current: AvatarRef
  avatars: AvatarChoice[] | null
}

export interface BankView {
  city_code: string
  city: string
  travelling: boolean
  no_city: boolean
  jailed: boolean
  cash: number
  bank: number
  withdrawal_fee_bps: number
  deposits: AmountOption[] | null
  withdrawals: AmountOption[] | null
  can_deposit: boolean
  can_withdraw: boolean
  notice: string
  notice_args: Record<string, unknown> | null
}

export interface BatchLotFailure {
  x: number
  y: number
  kind: string
}

export interface BidPlacedView {
  no: number
  item: Named
  amount: number
  method: string
  ends_at: string | null
}

export interface BillDecidedView {
  no: number
  place: Place
  subject: BillSubject
  body: string
  status: string
  lapsed_why: string
  yes: number
  nay: number
}

export interface BillRefusalView {
  kind: string
  no: number
  body: string
}

export interface BillSubject {
  kind: string
  code: string
  lever_type: string
  value: number
  allocation: Record<string, number> | null
  categories: string[] | null
  target: GovPlace | null
}

export interface BillView {
  no: number
  place: GovPlace
  subject: BillSubject
  office: string
  by: GovPlayer
  body: string
  rule: string
  threshold: string
  quorum: string
  seats: number
  held: number
  needs: number
  status: string
  lapsed_why: string
  yes: number
  nay: number
  votes: BillVoteLine[] | null
  closes_at: string | null
  remaining_seconds: number
  decided_ago_seconds: number
  can_vote: boolean
  notice: string
}

export interface BillVoteLine {
  player: GovPlayer
  yes: boolean
}

export interface BillsView {
  bills: BillView[] | null
}

export interface BoardLine {
  position: number
  code: string
  name: string
  tag: string
  tag_name: string
  city: Named
  value: number
  extra: number
  extra2: number
  mine: boolean
}

export interface BoardView {
  board: string
  lines: BoardLine[] | null
  at: string | null
  ranks: Record<string, Named> | null
}

export interface BookLevel {
  price: number
  qty: number
}

export interface BookSummary {
  item: Named
  best_bid: number
  best_ask: number
  last: number
}

export interface BookView {
  item: Named
  city_code: string
  city: string
  bids: BookLevel[] | null
  asks: BookLevel[] | null
  trades: TradeLine[] | null
  reference: number
  holding: number
  at_market: boolean
  way: Way | null
  nonce: string
}

export interface BudgetLineView {
  code: string
  effect: string
  spent: number
  effect_bps: number
}

export interface BudgetPeriodView {
  spent: number
  spendable: number
  lines: BudgetLineView[] | null
}

export interface BudgetView {
  no_city: boolean
  city: GovPlace
  lever: string
  can_propose: boolean
  spend_share_bps: number
  order: string[] | null
  allocation: Record<string, number> | null
  pending: Record<string, number> | null
  pending_in_seconds: number
  treasury: number
  last: BudgetPeriodView | null
  next_at: string | null
  next_in_seconds: number
}

export interface BuildLine {
  building: Named
  role: string
  state: string
  cost_money: number
  build_time_seconds: number
  missing: Named[] | null
  missing_buildings: Named[] | null
  materials: MaterialLine[] | null
  short: MaterialLine[] | null
}

export interface BuildMenuView {
  name: string
  treasury: number
  running_builds: number
  concurrent_cap: number
  lines: BuildLine[] | null
}

export interface BuildingEffectLine {
  target: string
  value: number
}

export interface BuildingResearchLine {
  knowledge: Named
  finish_at: string | null
  left_seconds: number
}

export interface BuildingStockLine {
  item: Named
  kind: string
  qty: number
}

export interface BuildingUpgradeLine {
  building: Named
  tier: number
  cost_money: number
  build_time_seconds: number
  available: boolean
  missing: Named[] | null
  needs_tier: string
}

export interface BuildingView {
  id: string
  building: Named
  role: string
  tier: number
  kind: string
  state: string
  mode: string
  x: number
  y: number
  w: number
  h: number
  rotated: boolean
  upkeep: number
  effects: BuildingEffectLine[] | null
  can_manage: boolean
  started_at: string | null
  finish_at: string | null
  left_seconds: number
  progress_percent: number
  stock: BuildingStockLine[] | null
  stock_used: number
  stock_capacity: number
  literacy_percent: number
  teaching: boolean
  treasury: number
  population: number
  research: BuildingResearchLine | null
  has_upgrade: boolean
  upgrades: BuildingUpgradeLine[] | null
}

export interface CandidateLine {
  player: GovPlayer
  mine: boolean
  votes: number
  counted: boolean
  elected: boolean
}

export interface CardView {
  name: string
  code: string
  avatar: AvatarRef
  bio: string
  rank: RankRef | null
  age: number
  stage: Named
  level: number
  achievements: number
  entries: number
  joined_at: string | null
  self: boolean
  photo: Photo | null
  notice: string
}

export interface CaseOutcomeView {
  crime: Named
  city_code: string
  city: string
  solved: boolean
  thief: string
  thief_code: string
  stolen: number
  restored: number
  shortfall: number
  fine: number
  fine_paid: number
  term_seconds: number
  returned: Named | null
}

export interface CityGovView {
  city: GovPlace
  sections: GovSection[] | null
  holds_office: boolean
  no_city: boolean
  tier: string
}

export interface CityMapView {
  city_code: string
  city: string
  no_city: boolean
  travelling: boolean
  travelling_to_code: string
  travelling_to: string
  here: Named
  walking: WalkView | null
  others: number
  places: PlaceLine[] | null
}

export interface ClinicTreatedView {
  ref: CompanyRef
  patient: string
  price: number
  item: Named
  units: number
  saved_seconds: number
}

export interface CompanyRef {
  code: string
  name: string
  type: Named
}

export interface ConstructionLine {
  id: string
  building: Named
  lot_x: number
  lot_y: number
  state: string
  finish_at: string | null
  left_seconds: number
  by_work: boolean
  progress_bps: number
  done_minutes: number
  required_minutes: number
  left_minutes: number
}

export interface ConstructionProgressView {
  name: string
  lines: ConstructionLine[] | null
  standing: StandingLine[] | null
}

export interface CourseRef {
  code: string
  name: string
}

export interface CreditView {
  score: number
  min: number
  max: number
  payment_bps: number
  debt_bps: number
  history_bps: number
  income_bps: number
  worth_bps: number
  new_credit_bps: number
  missed: number
  defaults: number
}

export interface DashboardView {
  name: string
  city_code: string
  city: string
  place: Named
  walk: WalkView | null
  level: number
  energy: number
  max_energy: number
  travelling: boolean
  cash: number
  bank: number
  jail: ProfileJail | null
}

export interface DeviceLine {
  id: string
  name: string
  via: string
  created_at: string | null
  last_seen_at: string | null
}

export interface DeviceLinkView {
  code: string
  expires_at: string | null
  valid_seconds: number
  mini_app_url: string
}

export interface DevicesView {
  devices: DeviceLine[] | null
  notice: string
}

export interface DiplomacyEntry {
  kind: string
  country: GovPlace
  other: GovPlace
  measures: string[] | null
  ground: string
  treaty: Named
  no: number
  by: GovPlayer | null
  office: string
  ago_seconds: number
}

export interface DiplomacyHistoryView {
  country: GovPlace
  entries: DiplomacyEntry[] | null
  page: number
  pages: number
}

export interface DiplomacyNotice {
  kind: string
  place: GovPlace
  treaty: Named
  in_seconds: number
}

export interface DiplomacyRefusalView {
  kind: string
  country: GovPlace
  office: string
  in_seconds: number
  back: Ref
}

export interface DismissView {
  office: string
  place: GovPlace
  seat: number
  holder: GovPlayer
}

export interface DividendView {
  company: Named
  free: number
  tax_bps: number
  total: number
  options: PriceOption[] | null
  chosen: PriceOption | null
  nonce: string
  paid: number
  per_share: number
  holders: number
  refused: string
}

export interface DonateView {
  village: string
  amount: number
  presets: number[] | null
  min: number
  max: number
  treasury: number
  cash: number
  settlement_id: string
}

export interface EffectLine {
  target: string
  op: string
  value: number
}

export interface ElectionLine {
  no: number
  office: string
  place: GovPlace
  phase: string
  seats: number
  ends_at: string | null
  remaining_seconds: number
  candidates: number
  elected: GovPlayer[] | null
}

export interface ElectionRefusalView {
  kind: string
  no: number
  office: string
  place: GovPlace
}

export interface ElectionResultView {
  no: number
  office: string
  place: Place
  elected: boolean
  votes: number
  cast: number
  deposit: number
  deposit_returned: boolean
}

export interface ElectionView {
  no: number
  office: string
  place: GovPlace
  seats: number
  phase: string
  remaining_seconds: number
  candidacy_ends_at: string | null
  voting_ends_at: string | null
  votes_cast: number
  candidates: CandidateLine[] | null
  deposit: number
  refund_share_bps: number
  min_level: number
  standing: boolean
  voted: boolean
  can_stand: boolean
  can_vote: boolean
  stand_blocked: string
  vote_blocked: string
  payment: PaymentChoice | null
  nonce: string
}

export interface ElectionsView {
  no_city: boolean
  place: GovPlace
  elections: ElectionLine[] | null
}

export interface EmptyView {
}

export interface EndTreatyView {
  country: GovPlace
  treaty: TreatyLine
}

export interface ErrorView {
  code: string
  args: Record<string, unknown> | null
}

export interface ExchangeView {
  lines: ListedLine[] | null
  unavailable: Unavailable | null
}

export interface FactionAnswerView {
  ref: FactionRef
  kind: string
  accepted: boolean
  player: Person
}

export interface FactionAnsweredView {
  ref: FactionRef
  kind: string
  accepted: boolean
  player: GovPlayer
}

export interface FactionAppliedView {
  ref: FactionRef
}

export interface FactionBankView {
  ref: FactionRef
  balance: number
  can_deposit: boolean
  can_withdraw: boolean
  cash: number
  bank_balance: number
  min: number
  max: number
  methods: string[] | null
  done: FactionMoneyDone | null
}

export interface FactionConfirmView {
  kind: string
  ref: FactionRef
  player: GovPlayer
}

export interface FactionCrimeBoardView {
  ref: FactionRef
  notice: string
  can_plan: boolean
  can_launch: boolean
  can_join: boolean
  cut_bps: number
  operation: FactionOperationLine | null
  in_crew: boolean
  crimes: FactionPlanLine[] | null
}

export interface FactionCrimeView {
  ref: FactionRef
  crime: Named
  result: string
  share: number
  take: number
  cut: number
  xp: number
  jail: Sentence | null
  fine: number
  fine_paid: number
  injury: Injury | null
}

export interface FactionFoundView {
  city_code: string
  city: string
  fee: number
  payment: PaymentChoice
  name_min: number
  name_max: number
}

export interface FactionFoundedView {
  ref: FactionRef
  city_code: string
  city: string
  fee: number
  method: string
}

export interface FactionHomeView {
  ref: FactionRef
  rank: string
  linked: boolean
  rights: string[] | null
  city_code: string
  city: string
  members: number
  max_members: number
  bank: number
  applications: number
  operation: FactionOperationLine | null
}

export interface FactionInvitedView {
  player: GovPlayer
}

export interface FactionLeftView {
  ref: FactionRef
  disbanded: boolean
  paid_out: number
}

export interface FactionLine {
  ref: FactionRef
  members: number
}

export interface FactionLinkedView {
  ref: FactionRef
}

export interface FactionListView {
  city_code: string
  city: string
  fee: number
  factions: FactionLine[] | null
  mine: FactionRef | null
}

export interface FactionMemberLine {
  player: GovPlayer
  rank: string
  self: boolean
  can_kick: boolean
  can_promote: boolean
  can_demote: boolean
  can_lead: boolean
}

export interface FactionMembersView {
  ref: FactionRef
  max: number
  can_invite: boolean
  members: FactionMemberLine[] | null
  requests: FactionRequestLine[] | null
}

export interface FactionMoneyDone {
  deposit: boolean
  amount: number
  method: string
}

export interface FactionOperationLine {
  no: number
  status: string
  crime: Named
  place: Named
  city_code: string
  city: string
  chance_bps: number
  min: number
  max: number
  nerve: number
  crew: FactionMemberLine[] | null
  left_seconds: number
  at: string | null
  expired: boolean
}

export interface FactionPageView {
  ref: FactionRef
  city_code: string
  city: string
  linked: boolean
  members: FactionMemberLine[] | null
  mine: boolean
  can_apply: boolean
  can_link: boolean
}

export interface FactionPlanLine {
  crime: Named
  min: number
  max: number
  nerve: number
  min_level: number
  duration_seconds: number
  places: Named[] | null
}

export interface FactionRef {
  code: string
  name: string
}

export interface FactionRefusalView {
  kind: string
  min: number
  max: number
  amount: number
  balance: number
  need: number
  have: number
  level: number
}

export interface FactionRequestLine {
  no: number
  kind: string
  player: GovPlayer
  can_decide: boolean
}

export interface FactionRequestView {
  no: number
  kind: string
  ref: FactionRef
  player: Person
}

export interface FinanceHubView {
  country: GovPlace
  credit: CreditView
  policy_bps: number
  products: LoanProductLine[] | null
  loans: LoanLine[] | null
  savings: number
  savings_bps: number
  lendable: number
  next_at: string | null
  notice: string
  args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface FinanceRefusalView {
  kind: string
  amount: number
  score: number
  count: number
  wait_seconds: number
  back: Ref
}

export interface FinanceView {
  kind: string
  no: number
  product: Named
  amount: number
  other: number
  count: number
  at: string | null
  pledge: Pledge | null
}

export interface FoundDraftView {
  founder: string
  pending: boolean
  minutes: number
  draft_id: string
}

export interface FoundingCheckedView {
  name: string
  currency_code: string
}

export interface FoundingChoiceView {
  code: string
  hex: string
}

export interface FoundingEmblemView {
  shape: string
  color_a: string
  color_b: string
  icon: string
}

export interface FoundingFormView {
  state: string
  draft: string
  expires_at: string | null
  founder: string
  suggested_name: string
  default_emblem: FoundingEmblemView
  limits: FoundingLimitsView
  shapes: FoundingChoiceView[] | null
  palette: FoundingChoiceView[] | null
  icons: FoundingChoiceView[] | null
  neutral_currency: string
  settlement_id: string
  settlement_name: string
}

export interface FoundingLimitsView {
  name_min: number
  name_max: number
  motto_max: number
  currency_name_min: number
  currency_name_max: number
  currency_code_len: number
  currency_symbol_max: number
}

export interface FoundingProblem {
  field: string
  code: string
}

export interface FoundingRefusalView {
  kind: string
  problems: FoundingProblem[] | null
  name: string
  limits: FoundingLimitsView
}

export interface FriendAcceptedView {
  name: string
}

export interface FriendLine {
  id: string
  name: string
  status: string
  incoming: boolean
}

export interface FriendRequestedView {
  name: string
}

export interface FriendsView {
  friends: FriendLine[] | null
  page: number
  pages: number
}

export interface GearLine {
  categories: Named[] | null
  crimes: Named[] | null
  success_bps: number
  catch_bps: number
  witness_bps: number
  solve_bps: number
  reward_bps: number
  nerve: number
  confiscated: boolean
}

export interface GoldPoint {
  price: number
  at: string | null
}

export interface GoldTradeView {
  side: string
  grams: number
  price: number
  total: number
  payment: PaymentChoice
  nonce: string
}

export interface GoldView {
  buy: number
  sell: number
  mid: number
  prev: number
  stock: number
  history: GoldPoint[] | null
  grams: number
  cost: number
  options: number[] | null
  next_at: string | null
  notice: string
  notice_args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface GovAppointee {
  office: string
  place: GovPlace
  seat: number
  holder: GovPlayer | null
  can_appoint: boolean
  can_dismiss: boolean
}

export interface GovHistoryEntry {
  place: GovPlace
  lever: string
  type: string
  office: string
  by: GovPlayer | null
  old: number
  new: number
  ago_seconds: number
  effective_in_seconds: number
}

export interface GovHistoryView {
  city: GovPlace
  entries: GovHistoryEntry[] | null
  page: number
  pages: number
}

export interface GovLever {
  code: string
  type: string
  value: number
  default: number
  min: number
  max: number
  from_office: boolean
  set_by: GovPlayer | null
  pending: GovPending | null
  held_by: string
  notice_seconds: number
  cooldown_seconds: number
  vote: boolean
  confirm_by: string
  allocation: Record<string, number> | null
  categories: string[] | null
}

export interface GovOffice {
  code: string
  seats: number
  holders: GovPlayer[] | null
  acting_code: string
  acting: GovPlayer[] | null
}

export interface GovPending {
  value: number
  allocation: Record<string, number> | null
  in_seconds: number
  by: GovPlayer | null
}

export interface GovPlace {
  kind: string
  code: string
  name: string
}

export interface GovPlayer {
  name: string
  code: string
}

export interface GovRefusal {
  kind: string
  office: string
  wait_seconds: number
}

export interface GovSeat {
  office: string
  place: GovPlace
  acting_for: string
  levers: GovLever[] | null
  vote_levers: GovLever[] | null
  appointees: GovAppointee[] | null
}

export interface GovSection {
  place: GovPlace
  offices: GovOffice[] | null
  levers: GovLever[] | null
}

export interface GridGrowView {
  settlement_name: string
  side: number
  new_side: number
  lots_gained: number
  buildable_gained: number
  price: number
  treasury: number
}

export interface HistoryLine {
  kind: string
  at: string | null
  code: string
  name: string
  sub: string
  sub_name: string
  place_kind: string
  place: Named
  amount: number
  number: number
  backfilled: boolean
  private: boolean
}

export interface HistoryView {
  name: string
  code: string
  self: boolean
  lines: HistoryLine[] | null
  page: number
  pages: number
  total: number
}

export interface HoldingLine {
  company: Named
  shares: number
  locked: number
  price: number
  value: number
  cost: number
  listed: boolean
}

export interface HospitalisedView {
  city_code: string
  city: string
  cause: string
  damage: number
  health: number
  max: number
  ends_at: string | null
  remaining_seconds: number
}

export interface ImposeView {
  country: GovPlace
  targets: GovPlace[] | null
  target: GovPlace | null
  mask: number
  measures: MeasureToggle[] | null
  chosen: string[] | null
  grounds: string[] | null
  ground: string
  notice_seconds: number
  min_duration_seconds: number
}

export interface InboxBadgeView {
  unread: number
  categories: InboxCategoryCount[] | null
  teaser: StoredNotice[] | null
}

export interface InboxCategoryCount {
  category: string
  count: number
}

export interface InboxCategoryView {
  category: string
  items: InboxItemLine[] | null
  page: number
  total_pages: number
}

export interface InboxHubCategory {
  category: string
  count: number
}

export interface InboxHubView {
  total: number
  categories: InboxHubCategory[] | null
}

export interface InboxItemLine {
  kind: string
  notice: StoredNotice
  ago_seconds: number
  link: Ref
}

export interface InboxReminderView {
  unread: number
}

export interface Injury {
  damage: number
  health: number
  max: number
  hospital: boolean
  ends_at: string | null
}

export interface InsuranceProductLine {
  product: Named
  covers: string
  premium: number
  prem_bps: number
  cover_bps: number
  max_claim: number
  waiting_seconds: number
  targets: PledgeLine[] | null
  held: boolean
}

export interface InsuranceView {
  country: GovPlace
  fund: number
  products: InsuranceProductLine[] | null
  policies: PolicyLine[] | null
  notice: string
  notice_args: Record<string, unknown> | null
  cancel: PolicyLine | null
  unavailable: Unavailable | null
}

export interface InsureConfirmView {
  product: Named
  covers: string
  property: PledgeLine | null
  premium: number
  cover_bps: number
  max_claim: number
  waiting_seconds: number
  payment: PaymentChoice
}

export interface InventoryLine {
  item: Named
  category: string
  qty: number
  serial: string
  quality: number
  uses_left: number
  durability: number
  design: string
}

export interface InventoryView {
  lines: InventoryLine[] | null
  page: number
  pages: number
  total: number
  in_escrow: number
}

export interface ItemDetailView {
  item: Named
  category: string
  qty: number
  ref: string
  piece: boolean
  quality: number
  uses_left: number
  durability: number
  worth: number
  effects: EffectLine[] | null
  gear: GearLine | null
  usable: boolean
  tradeable: boolean
  cooldown_seconds: number
  cooling_for_seconds: number
  ready_at: string | null
  nonce: string
  give_to: Named[] | null
}

export interface ItemDroppedView {
  item: Named
  ref: string
  nonce: string
}

export interface ItemGivenView {
  item: Named
  to: Named
}

export interface ItemRefusalView {
  kind: string
  item: Named
  wait_seconds: number
  ready_at: string | null
}

export interface ItemUsedView {
  item: Named
  changes: VitalChange[] | null
  left: number
  cooldown_seconds: number
  ready_at: string | null
}

export interface JobRef {
  career_code: string
  career_name: string
  rank: string
  title: string
}

export interface KnowledgeLine {
  knowledge: Named
  state: string
  research_cost: number
  research_time_seconds: number
  buy_price: number
  missing: Named[] | null
  terrain_ok: boolean
}

export interface KnowledgeListView {
  name: string
  treasury: number
  literacy_percent: number
  running: KnowledgeResearchLine | null
  lines: KnowledgeLine[] | null
  hidden: number
}

export interface KnowledgeResearchLine {
  knowledge: Named
  finish_at: string | null
  left_seconds: number
}

export interface LaborBoardView {
  village: string
  jobs: LaborJobLine[] | null
  market: LaborMarketLine
  working: LaborShiftLine | null
  resident: boolean
  sites: LaborSiteRef[] | null
}

export interface LaborJobLine {
  id: string
  building_id: string
  building: Named
  kind: string
  employer_kind: string
  employer: string
  wage: number
  left: number
  total: number
  progress_bps: number
  left_minutes: number
  workers: number
  npc_crew: number
  can_take: boolean
  mine: boolean
  points: number
}

export interface LaborMarketLine {
  housing: number
  pool: number
  available: number
  working: number
  vacancies: number
  tightness_bps: number
  level: string
  npc_wage: number
  min_wage: number
}

export interface LaborMineView {
  village: string
  shifts: number
  earned: number
  level: string
  productivity_bps: number
  next_level: string
  next_shifts: number
  working: LaborShiftLine | null
  market: LaborMarketLine
}

export interface LaborPreset {
  percent: number
  wage: number
}

export interface LaborShiftLine {
  id: string
  building: Named
  kind: string
  worker: string
  worker_npc: boolean
  level: string
  finish_at: string | null
  left_seconds: number
  wage: number
  points: number
}

export interface LaborSiteRef {
  id: string
  building: Named
  progress_bps: number
}

export interface LaborSiteView {
  village: string
  building: Named
  id: string
  status: string
  progress_bps: number
  required_minutes: number
  done_minutes: number
  left_minutes: number
  job: LaborJobLine | null
  workers: LaborShiftLine[] | null
  market: LaborMarketLine
  can_work: boolean
  work_wage: number
  work_points: number
  working: LaborShiftLine | null
  can_employ: boolean
  can_post: boolean
  hire_presets: number[] | null
  wage_presets: LaborPreset[] | null
  npc_available: number
  npc_wage: number
  just: string
}

export interface LandCell {
  x: number
  y: number
  state: string
  owner: string
  building: string
  access: string
  roads: number
  crossings: number
  cost: number
}

export interface LandView {
  village: string
  settlement_id: string
  grid_lots: number
  rows: (LandCell[] | null)[] | null
  price: number
  cash: number
  owned: number
  max: number
  can_buy: boolean
  free_lots: number
  served_lots: number
}

export interface LeverEditView {
  place: GovPlace
  lever: GovLever
  draft: number
  fine_step: number
  coarse_step: number
  next_change_in_seconds: number
}

export interface LifeRefusalView {
  kind: string
  wait_seconds: number
  min: number
  max: number
}

export interface LifeView {
  needs: NeedsView
  age: number
  stage: Named
  intelligence: number
  intelligence_max: number
  course_bps: number
  skill_bps: number
  rank: RankRef | null
  next: RankRef | null
  next_need: number
  worth: WorthView
  spots: SleepSpotLine[] | null
  sleep_in_seconds: number
  home: boolean
  notice: string
  notice_args: Record<string, unknown> | null
}

export interface LiftView {
  country: GovPlace
  sanction: SanctionLine
}

export interface ListedLine {
  company: Named
  type: Named
  city: GovPlace
  price: number
  prev: number
  volume: number
  cap: number
}

export interface ListingView {
  company: Named
  refused: string
  age_seconds: number
  min_age_seconds: number
  revenue: number
  min_revenue: number
  book: number
  total: number
  fee: number
  floats: PriceOption[] | null
  prices: PriceOption[] | null
  chosen: PriceOption | null
  nonce: string
}

export interface LoanConfirmView {
  product: Named
  amount: number
  term: number
  rate_bps: number
  interest: number
  instalment: number
  total: number
  first_at: string | null
  pledge: PledgeLine | null
  nonce: string
}

export interface LoanDetailView {
  loan: LoanLine
  principal: number
  interest: number
  rate_bps: number
  periods: number
  paid: number
  fees_due: number
  payoff: number
  pledge: PledgeLine | null
  opened_at: string | null
  next_at: string | null
  missed: number
  recovered: number
  written_off: number
  nonce: string
  notice: string
  notice_args: Record<string, unknown> | null
  confirm_open: boolean
}

export interface LoanLine {
  no: number
  product: Named
  company: Named
  status: string
  next: number
  owed: number
  left: number
  arrears: number
}

export interface LoanOfferView {
  product: Named
  kind: string
  rate_bps: number
  limit: number
  terms: number[] | null
  options: LoanOption[] | null
  pledges: PledgeLine[] | null
  pledge: PledgeLine | null
  late_fee_bps: number
  default_after: number
  unavailable: Unavailable | null
}

export interface LoanOption {
  amount: number
  term: number
  instalment: number
}

export interface LoanProductLine {
  product: Named
  kind: string
  rate_bps: number
  limit: number
  min_score: number
}

export interface Loot {
  item: Named
  qty: number
}

export interface LotAccess {
  kind: string
  roads: number
  crossings: number
  cost: number
  carved: LotRef[] | null
  path: LotRef[] | null
}

export interface LotAccessView {
  village: string
  settlement_id: string
  x: number
  y: number
  own: boolean
  price: number
  refund: number
  cash: number
  access: LotAccess
  carve: LotAccess | null
  nearby: LotNearby[] | null
  building: Named
}

export interface LotBatchConfirmView {
  settlement_name: string
  building: Named
  lots: LotBatchLot[] | null
  count: number
  cost_money: number
  materials: MaterialLine[] | null
  build_time_seconds: number
}

export interface LotBatchLot {
  x: number
  y: number
}

export interface LotBuyView {
  village: string
  settlement_id: string
  x: number
  y: number
  price: number
  cash: number
  treasury: number
  access: LotAccess
  carve: LotAccess | null
  nearby: LotNearby[] | null
  road: string
  total: number
}

export interface LotCell {
  x: number
  y: number
  state: string
  own: boolean
  fits: boolean
}

export interface LotConfirmView {
  settlement_name: string
  building: Named
  x: number
  y: number
  rotated: boolean
  cost_money: number
  materials: MaterialLine[] | null
  build_time_seconds: number
  auto_roads: number
}

export interface LotGridView {
  settlement_name: string
  building: Named
  can_rotate: boolean
  rotated: boolean
  grid_lots: number
  rows: (LotCell[] | null)[] | null
  multi: boolean
  line: string
  from: LotBatchLot
  win_x: number
  win_y: number
}

export interface LotNearby {
  x: number
  y: number
  distance: number
  access: LotAccess
}

export interface LotRef {
  x: number
  y: number
}

export interface LotRepairView {
  village: string
  settlement_id: string
  x: number
  y: number
  option: string
  paid: number
  refund: number
  cash: number
  roads: number
  crossings: number
  carved: number
}

export interface MapCity {
  code: string
  name: string
  distance_km: number
  emblem: string
  village: boolean
  settlement_id: string
  lat: number
  lon: number
  fare: number
  wait_seconds: number
}

export interface MapView {
  destinations: MapCity[] | null
  page: number
  pages: number
  origin_code: string
  origin: string
  travelling: boolean
  travelling_to_code: string
  travelling_to: string
}

export interface MarketCheckoutView {
  item: Named
  qty: number
  price: number
  reserve: number
  payment: PaymentChoice
  nonce: string
}

export interface MarketFilledView {
  side: string
  item: Named
  qty: number
  price: number
  amount: number
  fee: number
  city_code: string
  city: string
}

export interface MarketRefusalView {
  kind: string
  item: Named
  count: number
}

export interface MarketView {
  city_code: string
  city: string
  books: BookSummary[] | null
  yours: Named[] | null
  at_market: boolean
  way: Way | null
}

export interface MaterialBought {
  item: Named
  qty: number
  total: number
}

export interface MaterialBuyView {
  village: string
  item: Named
  qty: number
  unit: number
  total: number
  treasury: number
  free: number
}

export interface MaterialLine {
  component: Named
  quantity: number
}

export interface MaterialMarketLine {
  item: Named
  price: number
}

export interface MaterialStockLine {
  item: Named
  qty: number
}

export interface MaterialsView {
  village: string
  treasury: number
  stock: MaterialStockLine[] | null
  used: number
  capacity: number
  market: MaterialMarketLine[] | null
  can_buy: boolean
  presets: number[] | null
  bought: MaterialBought | null
}

export interface MeasureToggle {
  code: string
  on: boolean
  mask: number
}

export interface MineLot {
  x: number
  y: number
  access: string
  cost: number
  building: string
  state: string
  finish_at: string | null
  left_seconds: number
}

export interface MineView {
  village: string
  settlement_id: string
  cash: number
  lots: MineLot[] | null
  home: Named | null
  can_rest: boolean
  rest_wait_seconds: number
  assessed: number
  tax_per_period: number
  tax_bps: number
  debt: number
  debt_periods: number
  notice: string
}

export interface MissionCompletedView {
  mission: Named
  cash: number
  withheld: number
  xp: number
  items: Loot[] | null
}

export interface MyAuctionsView {
  auctions: AuctionLine[] | null
}

export interface MyOfficeView {
  seats: GovSeat[] | null
}

export interface MyOrdersView {
  orders: OrderLine[] | null
}

export interface Named {
  code: string
  name: string
}

export interface NeedBuilding {
  code: string
  role: string
  tier: number
}

export interface NeedsView {
  hunger: number
  sleep: number
  stress: number
  happiness: number
  body_bps: number
  xpbps: number
  pressing: string[] | null
}

export interface NotHereView {
  need: string
  need_args: Record<string, unknown> | null
  mode: string
  crime: Named
  shop: Named
  place: Named
  here: Named
  walk_seconds: number
  walking: boolean
  remaining_seconds: number
  arrives_at: string | null
  then: string
  then_args: string[] | null
}

export interface OfficeView {
  office: string
  place: Place
  by: Person
  by_office: string
  dismissed: boolean
}

export interface OpenOrderLine {
  no: number
  company: Named
  side: string
  qty: number
  filled: number
  price: number
}

export interface OrderCancelledView {
  item: Named
  side: string
  no: number
  left: number
  refund: number
}

export interface OrderLine {
  no: number
  item: Named
  side: string
  qty: number
  filled: number
  price: number
  status: string
  city_code: string
  city: string
  expires_at: string | null
}

export interface OrderPlacedView {
  item: Named
  side: string
  no: number
  qty: number
  filled: number
  price: number
  rests: boolean
  spent: number
  got: number
  expires_at: string | null
  method: string
  embargoed: number
}

export interface PayConfirmView {
  payee_name: string
  payee_code: string
  method: string
  amount: number
  fee: number
  total: number
  after: number
  nonce: string
  origin: string
}

export interface PayHelpView {
}

export interface PaySentView {
  payee_name: string
  payee_code: string
  method: string
  amount: number
  fee: number
  held: boolean
}

export interface PayView {
  payee_name: string
  payee_code: string
  together: boolean
  city_code: string
  city: string
  payer_city_code: string
  payer_city: string
  card_fee_bps: number
  cash: number
  bank: number
  cash_options: AmountOption[] | null
  card_options: AmountOption[] | null
  can_cash: boolean
  can_card: boolean
  origin: string
  notice: string
  notice_args: Record<string, unknown> | null
}

export interface PaymentChoice {
  amount: number
  accepted: string[] | null
  usable: string[] | null
  cash: number
  bank: number
}

export interface PaymentDeclinedView {
  amount: number
  cash: number
  bank: number
  accepted: string[] | null
  back_label: string
  back: Ref
}

export interface PaymentView {
  payer_name: string
  payer_code: string
  method: string
  amount: number
}

export interface Person {
  name: string
  code: string
}

export interface Photo {
  file_id: string
  user_id: number
  player_id: string
}

export interface Place {
  kind: string
  code: string
  name: string
}

export interface PlaceLine {
  place: Named
  walk_seconds: number
  energy: number
  services: string[] | null
  departures: string[] | null
  shops: Named[] | null
  here: boolean
}

export interface Pledge {
  no: number
  code: string
  type: Named
  city: Place
  value: number
  limit: number
}

export interface PledgeLine {
  no: number
  code: string
  type: Named
  city: GovPlace
  value: number
  limit: number
}

export interface PolicyAnnouncedView {
  place: GovPlace
  lever: GovLever
  old: number
  new: number
  old_allocation: Record<string, number> | null
  new_allocation: Record<string, number> | null
  in_seconds: number
}

export interface PolicyConfirmView {
  place: GovPlace
  lever: GovLever
  new_value: number
  vote_by: string
}

export interface PolicyLine {
  no: number
  product: Named
  covers: string
  property: PledgeLine | null
  status: string
  reason: string
  premium: number
  paid: number
  from: string | null
  started: string | null
  claimable: boolean
}

export interface PolicyRefusalView {
  refusal: GovRefusal
  place: GovPlace | null
  lever: GovLever | null
}

export interface PortfolioView {
  holdings: HoldingLine[] | null
  orders: OpenOrderLine[] | null
  gold: number
  gold_val: number
  savings: number
  value: number
  gain: number
  notice: string
  notice_args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface PriceOption {
  qty: number
  price: number
}

export interface PrivateConfirmView {
  village: string
  building: Named
  x: number
  y: number
  rotated: boolean
  cost_money: number
  permit_fee: number
  materials: PrivateMaterial[] | null
  materials_cost: number
  total: number
  cash: number
  build_time_seconds: number
}

export interface PrivateLine {
  building: Named
  home: boolean
  class: string
  cost_money: number
  permit_fee: number
  materials: PrivateMaterial[] | null
  build_time_seconds: number
  footprint_w: number
  footprint_h: number
  total: number
  affordable: boolean
}

export interface PrivateLotsView {
  village: string
  building: Named
  can_rotate: boolean
  rotated: boolean
  grid_lots: number
  rows: (LotCell[] | null)[] | null
}

export interface PrivateMaterial {
  component: Named
  need: number
  have: number
  buy: number
  buy_cost: number
}

export interface PrivateMenuView {
  village: string
  settlement_id: string
  cash: number
  owned_lots: number
  free_lots: number
  lines: PrivateLine[] | null
}

export interface ProfileCourse {
  course: CourseRef
  remaining_seconds: number
  paused: boolean
}

export interface ProfileJail {
  city_code: string
  city: string
  remaining_seconds: number
  ends_at: string | null
}

export interface ProfileJob {
  job: JobRef
  city_code: string
  city: string
  pay: number
  shift_ends_in_seconds: number
}

export interface ProfileView {
  name: string
  code: string
  city_code: string
  city: string
  place: Named
  walk: WalkView | null
  level: number
  xp: number
  next_level_xp: number
  energy: number
  max_energy: number
  energy_full_in_seconds: number
  health: number
  max_health: number
  cash: number
  bank: number
  travelling: boolean
  travel_to_code: string
  travel_to: string
  travel_remaining_seconds: number
  work: ProfileWork | null
  jail: ProfileJail | null
  hospital: ProfileJail | null
  achievements: number
  avatar: string
  rank: RankRef | null
  age: number
  stage: Named
  needs: NeedsView | null
  village: Named | null
}

export interface ProfileWork {
  job: ProfileJob | null
  course: ProfileCourse | null
  certificates: number
}

export interface PromotionCriterionView {
  kind: string
  role: string
  current: number
  required: number
  met: boolean
}

export interface PromotionView {
  village: string
  from: string
  to: string
  criteria: PromotionCriterionView[] | null
  met: boolean
  can_promote: boolean
  office: string
  settlement_id: string
}

export interface PropertyDetailView {
  property: PropertyLine
  place: Named
  upkeep: number
  tax_bps: number
  max_price: number
  max_rent: number
  notice: string
}

export interface PropertyLeaveView {
  lease_no: number
  type: Named
  city: GovPlace
}

export interface PropertyLine {
  no: number
  type: Named
  kind: string
  size: number
  quality: number
  city: GovPlace
  value: number
  debt: number
  unpaid_periods: number
  home: boolean
  offer: PropertyOfferLine | null
  tenant: GovPlayer | null
  rent: number
  arrears: number
}

export interface PropertyMarketView {
  no_city: boolean
  city: GovPlace
  types: PropertyTypeLine[] | null
  offers: PropertyOfferLine[] | null
}

export interface PropertyMineView {
  owned: PropertyLine[] | null
  rented: RentedHomeLine | null
  residence: GovPlace
  grace: number
  can_rest: boolean
  rest_in_seconds: number
  rest_energy: number
  notice: string
  notice_args: Record<string, unknown> | null
}

export interface PropertyOfferLine {
  no: number
  kind: string
  type: Named
  property_no: number
  price: number
  seller: GovPlayer
  mine: boolean
}

export interface PropertyOfferView {
  offer: PropertyOfferLine
  city: GovPlace
  kind: string
  size: number
  quality: number
  upkeep: number
  home: boolean
  payment: PaymentChoice | null
  blocked: string
  max: number
  way: Way | null
}

export interface PropertyRefusalView {
  kind: string
  max: number
  wait_seconds: number
  back: Ref
}

export interface PropertyTypeLine {
  type: Named
  kind: string
  size: number
  quality: number
  price: number
  left: number
  home: boolean
}

export interface PropertyTypeView {
  city: GovPlace
  type: Named
  kind: string
  size: number
  quality: number
  upkeep: number
  home: boolean
  rest_energy: number
  place: Named
  price: number
  left: number
  tax_bps: number
  payment: PaymentChoice | null
  blocked: string
  max: number
  way: Way | null
  bought: number
}

export interface PropertyView {
  kind: string
  type: Named
  no: number
  city: Place
  player: Person
  amount: number
}

export interface ProposeView {
  country: GovPlace
  partners: GovPlace[] | null
  partner: GovPlace | null
  kinds: Named[] | null
  kind: Named | null
  ttl_seconds: number
}

export interface Rank {
  code: string
  name: string
  emoji: string
}

export interface RankRef {
  code: string
  name: string
  emoji: string
}

export interface RankView {
  rank: Rank
  from: Rank
  up: boolean
  worth: number
}

export interface RecruitView {
  kind: string
  company: CompanyRef
  campaign_no: number
  count: number
  name_seed: number
  skill: string
  level: number
  reason: string
  amount: number
}

export interface Ref {
  command: string
  args: string[] | null
}

export interface RefusalView {
  kind: string
  missing: Requirement[] | null
  city_code: string
  city: string
  fee: number
  cash: number
  wait_seconds: number
  ends_at: string | null
}

export interface RentedHomeLine {
  lease_no: number
  property: PropertyLine
  landlord: GovPlayer
  rent: number
  arrears: number
}

export interface Requirement {
  kind: string
  met: boolean
  skill: string
  need: number
  have: number
  course_code: string
  course_name: string
  city_code: string
  city: string
  wait_seconds: number
}

export interface ResidenceView {
  leaving: boolean
  village: string
  home: string
  home_code: string
  cooldown_seconds: number
  population: number
  settlement_id: string
}

export interface SanctionBlockedView {
  measure: string
  imposer: GovPlace
  target: GovPlace
  back: Ref
}

export interface SanctionLine {
  no: number
  imposer: GovPlace
  target: GovPlace
  measures: string[] | null
  ground: string
  by: GovPlayer | null
  office: string
  since_seconds: number
  in_force_in_seconds: number
  liftable: boolean
  liftable_in_seconds: number
}

export interface SanctionsView {
  country: GovPlace
  imposed: SanctionLine[] | null
  suffered: SanctionLine[] | null
  can_impose: boolean
  notice: DiplomacyNotice | null
}

export interface SavingsView {
  balance: number
  rate_bps: number
  earned: number
  next: number
  bank: number
  deposits: number[] | null
  withdrawals: number[] | null
  next_at: string | null
  notice: string
  notice_args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface SearchResult {
  id: string
  name: string
  code: string
  self: boolean
}

export interface SearchView {
  help: boolean
  by: string
  query: string
  found: SearchResult | null
}

export interface SellOffer {
  shop: Named
  place: Named
  price: number
}

export interface SellOffersView {
  item: Named
  ref: string
  offers: SellOffer[] | null
}

export interface Sentence {
  crime: Named
  remaining_seconds: number
  ends_at: string | null
}

export interface SettingsView {
  language: string
  languages: string[] | null
  language_changed: boolean
  presence_visibility: string
  presence_changed: boolean
}

export interface SettlementFoundedView {
  name: string
  settlement_id: string
  biome_code: string
  nearby_feature: string
  buildings: string[] | null
  protected_until: string | null
  founder: string
  emblem: FoundingEmblemView
  motto: string
  currency_name: string
  currency_code: string
  currency_symbol: string
}

export interface SettlementRefusalView {
  kind: string
  name: string
}

export interface SettlementWhoView {
  name: string
  online: WhoLine[] | null
  offline: number
}

export interface ShelfLine {
  item: Named
  price: number
  stock: number
  busy: boolean
  buyback: number
  next_restock: string | null
}

export interface ShopBoughtView {
  shop: Named
  item: Named
  qty: number
  total: number
  tax: number
  method: string
}

export interface ShopCheckoutView {
  shop: Named
  item: Named
  qty: number
  unit: number
  total: number
  tax: number
  tax_bps: number
  stock: number
  payment: PaymentChoice
  nonce: string
}

export interface ShopLine {
  shop: Named
  place: Named
  here: boolean
}

export interface ShopRefusalView {
  kind: string
  shop: Named
  item: Named
  stock: number
  next_restock: string | null
}

export interface ShopSoldView {
  shop: Named
  item: Named
  price: number
  left: number
}

export interface ShopView {
  shop: Named
  place: Named
  here: boolean
  walk_seconds: number
  shelves: ShelfLine[] | null
  tax_bps: number
}

export interface ShopsView {
  city_code: string
  city: string
  shops: ShopLine[] | null
  place: Named | null
}

export interface SleepPayView {
  spot: Named
  rest: number
  relief: number
  payment: PaymentChoice
}

export interface SleepSpotLine {
  spot: Named
  place: Named
  price: number
  rest: number
  relief: number
  way: Way | null
}

export interface StandingLine {
  id: string
  building: Named
  lot_x: number
  lot_y: number
}

export interface StockOrderView {
  company: Named
  side: string
  qty: number
  price: number
  reserve: number
  bank: number
  fee_bps: number
  nonce: string
  placed: boolean
  no: number
  filled: number
  spent: number
  got: number
  rests: boolean
  expires_at: string | null
}

export interface StockPageView {
  company: Named
  type: Named
  city: GovPlace
  listed: boolean
  price: number
  prev: number
  ipo: number
  book: number
  total: number
  bids: BookLevel[] | null
  asks: BookLevel[] | null
  trades: TradeLine[] | null
  holding: number
  locked: number
  cost: number
  owner: boolean
  controller: string
  buys: PriceOption[] | null
  sells: PriceOption[] | null
  last_div: number
  fee_bps: number
  notice: string
  notice_args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface StockView {
  kind: string
  company: Named
  side: string
  qty: number
  price: number
  amount: number
  player: string
}

export interface StoodView {
  no: number
  office: string
  place: GovPlace
  deposit: number
  method: string
  voting_at: string | null
  voting_in_seconds: number
}

export interface StoredNotice {
  screen: string
  view: unknown
  text: string
}

export interface TermsView {
  village: string
  settlement_id: string
  lot_price: number
  lot_price_min: number
  lot_price_max: number
  permit_fee: number
  permit_fee_max: number
  tax_bps: number
  tax_bps_max: number
  lot_presets: number[] | null
  permit_presets: number[] | null
  tax_presets: number[] | null
  default_lot_price: number
  default_permit: number
  default_tax_bps: number
}

export interface TradeLine {
  qty: number
  price: number
  at: string | null
}

export interface TravelArrivedView {
  city_code: string
  city: string
  xp: number
}

export interface TravelCheckoutView {
  from_code: string
  from: string
  to_code: string
  to: string
  mode_code: string
  mode_name: string
  fare: number
  wait_seconds: number
  energy: number
  busy: boolean
  payment: PaymentChoice
}

export interface TravelHereView {
  reason: string
  village: string
  village_code: string
}

export interface TravelOption {
  mode_code: string
  mode_name: string
  fare: number
  wait_seconds: number
  energy: number
  busy: boolean
  vehicle: Named | null
  condition: number
}

export interface TravelOptionsView {
  from_code: string
  from: string
  to_code: string
  to: string
  options: TravelOption[] | null
  cash: number
  requoted: boolean
}

export interface TravelStartedView {
  from_code: string
  from: string
  to_code: string
  to: string
  mode_code: string
  mode_name: string
  duration_seconds: number
  arrives_at: string | null
  energy: number
  fare: number
}

export interface TravelStatusView {
  from_code: string
  from: string
  to_code: string
  to: string
  mode_code: string
  mode_name: string
  remaining_seconds: number
  arrives_at: string | null
}

export interface TreatiesView {
  country: GovPlace
  treaties: TreatyLine[] | null
  can_act: boolean
  notice: DiplomacyNotice | null
}

export interface TreatyLine {
  no: number
  kind: Named
  other: GovPlace
  status: string
  incoming: boolean
  expires_in_seconds: number
  since_seconds: number
}

export interface TreatyView {
  country: Place
  other: Place
  kind: Named
  no: number
  ttl_seconds: number
}

export interface Unavailable {
  service: string
  stage: string
  here: string
  requires: NeedBuilding[] | null
  nearest: Named | null
}

export interface VictimView {
  crime: Named
  venue: Named
  city_code: string
  city: string
  amount: number
  thief_name: string
  thief_code: string
  crime_id: string
  report_fee: number
  report_within_seconds: number
  item: Named | null
}

export interface VillageMaker {
  building: Named
  built: boolean
}

export interface VillageNeed {
  kind: string
  item: Named
  options: Named[] | null
  have: number
  need: number
  makers: VillageMaker[] | null
  price: number
}

export interface VillageNewsItem {
  kind: string
  building: Named
  knowledge: Named
  percent: number
  player: string
  amount: number
  tier: string
}

export interface VillageNewsView {
  village: string
  items: VillageNewsItem[] | null
}

export interface VillageOverviewView {
  name: string
  tier: string
  population: number
  population_cap: number
  food_percent: number
  job_percent: number
  service_percent: number
  happiness_percent: number
  security_percent: number
  literacy_percent: number
  resident: boolean
  settlement_id: string
  treasury: number
  buildings: VillageRoleLine[] | null
  is_head: boolean
  support: VillageSupport | null
  promotion: PromotionView | null
}

export interface VillageRefusalView {
  kind: string
  back: Ref
  remaining_seconds: number
  min: number
  max: number
  lots: BatchLotFailure[] | null
  action: string
  subject: Named
  needs: VillageNeed[] | null
}

export interface VillageRoleLine {
  role: string
  building: Named
  tier: number
}

export interface VillageSupport {
  code: string
  name: string
  services: string[] | null
}

export interface VitalChange {
  target: string
  before: number
  after: number
  max: number
}

export interface VotedView {
  no: number
  office: string
  place: GovPlace
  candidate: GovPlayer
  count_at: string | null
  count_in_seconds: number
}

export interface WalkStartedView {
  from: Named
  to: Named
  duration_seconds: number
  arrives_at: string | null
  energy: number
  then: string
}

export interface WalkView {
  to: Named
  remaining_seconds: number
  arrives_at: string | null
}

export interface Way {
  place: Named
  walk_seconds: number
}

export interface WhoLine {
  name: string
  activity: string
  place: string
}

export interface WorkShiftLine {
  building: Named
  finish_at: string | null
  left_seconds: number
  wage: number
  produces: MaterialLine[] | null
}

export interface WorkView {
  village: string
  resident: boolean
  places: WorkplaceLine[] | null
  mine: WorkShiftLine | null
  suggest: Named[] | null
  started: boolean
  used: number
  capacity: number
}

export interface WorkplaceLine {
  id: string
  building: Named
  produces: MaterialLine[] | null
  consumes: MaterialLine[] | null
  wage: number
  shift_seconds: number
  workers: number
  busy: number
  ready: boolean
}

export interface WorthView {
  cash: number
  bank: number
  escrow: number
  equity: number
  property: number
  goods: number
  debts: number
  savings: number
  gold: number
  loans: number
  total: number
}

/** The screens of the migrated areas: the screen name on the wire, and its view. */
export interface ScreenViews {
  achievement_notice: AchievementView
  achievements: AchievementsView
  allocation_confirm: AllocationConfirmView
  allocation_edit: AllocationEditView
  appoint_confirm: AppointView
  appoint_done: AppointDoneView
  appoint_refusal: AppointRefusalView
  auction_detail: AuctionDetailView
  auction_new: AuctionNewView
  auction_notice: AuctionView
  auction_opened: AuctionOpenedView
  auction_refusal: AuctionRefusalView
  auctions: AuctionsView
  avatars: AvatarsView
  bank: BankView
  bid_placed: BidPlacedView
  bill: BillView
  bill_decided_notice: BillDecidedView
  bill_refusal: BillRefusalView
  bills: BillsView
  book: BookView
  budget: BudgetView
  card: CardView
  case_solved_notice: CaseOutcomeView
  cities: MapView
  city_governance: CityGovView
  city_map: CityMapView
  clinic_treated_notice: ClinicTreatedView
  convicted_notice: CaseOutcomeView
  dashboard: DashboardView
  device_link: DeviceLinkView
  devices: DevicesView
  diplomacy_history: DiplomacyHistoryView
  diplomacy_refusal: DiplomacyRefusalView
  dismiss_confirm: DismissView
  dividend: DividendView
  drop_confirm: ItemDroppedView
  election: ElectionView
  election_refusal: ElectionRefusalView
  election_result_notice: ElectionResultView
  elections: ElectionsView
  end_treaty: EndTreatyView
  error: ErrorView
  exchange: ExchangeView
  faction_answer_notice: FactionAnswerView
  faction_answered: FactionAnsweredView
  faction_applied: FactionAppliedView
  faction_bank: FactionBankView
  faction_confirm: FactionConfirmView
  faction_crime: FactionCrimeBoardView
  faction_crime_notice: FactionCrimeView
  faction_found: FactionFoundView
  faction_founded: FactionFoundedView
  faction_home: FactionHomeView
  faction_invited: FactionInvitedView
  faction_left: FactionLeftView
  faction_linked: FactionLinkedView
  faction_list: FactionListView
  faction_members: FactionMembersView
  faction_page: FactionPageView
  faction_refusal: FactionRefusalView
  faction_request_notice: FactionRequestView
  finance_hub: FinanceHubView
  finance_notice: FinanceView
  finance_refusal: FinanceRefusalView
  founding_checked: FoundingCheckedView
  founding_form: FoundingFormView
  founding_refusal: FoundingRefusalView
  friend_accepted: FriendAcceptedView
  friend_requested: FriendRequestedView
  friends: FriendsView
  gold: GoldView
  gold_trade: GoldTradeView
  gov_history: GovHistoryView
  history: HistoryView
  hospitalised_notice: HospitalisedView
  hunger_notice: EmptyView
  impose: ImposeView
  inbox_badge: InboxBadgeView
  inbox_category: InboxCategoryView
  inbox_hub: InboxHubView
  inbox_reminder: InboxReminderView
  insurance: InsuranceView
  insure_confirm: InsureConfirmView
  inventory: InventoryView
  item_detail: ItemDetailView
  item_dropped: ItemDroppedView
  item_given: ItemGivenView
  item_refusal: ItemRefusalView
  item_used: ItemUsedView
  labor_board: LaborBoardView
  labor_mine: LaborMineView
  labor_site: LaborSiteView
  leaderboard: BoardView
  lever_edit: LeverEditView
  life: LifeView
  life_refusal: LifeRefusalView
  lift: LiftView
  listing: ListingView
  loan_confirm: LoanConfirmView
  loan_detail: LoanDetailView
  loan_offer: LoanOfferView
  market: MarketView
  market_checkout: MarketCheckoutView
  market_filled_notice: MarketFilledView
  market_refusal: MarketRefusalView
  mission_completed_notice: MissionCompletedView
  my_auctions: MyAuctionsView
  my_office: MyOfficeView
  my_orders: MyOrdersView
  not_here: NotHereView
  office_notice: OfficeView
  order_cancelled: OrderCancelledView
  order_placed: OrderPlacedView
  pay: PayView
  pay_confirm: PayConfirmView
  pay_help: PayHelpView
  pay_sent: PaySentView
  payment_declined: PaymentDeclinedView
  payment_notice: PaymentView
  policy_announced: PolicyAnnouncedView
  policy_confirm: PolicyConfirmView
  policy_refused: PolicyRefusalView
  portfolio: PortfolioView
  profile: ProfileView
  property: PropertyDetailView
  property_leave: PropertyLeaveView
  property_market: PropertyMarketView
  property_mine: PropertyMineView
  property_notice: PropertyView
  property_offer: PropertyOfferView
  property_refusal: PropertyRefusalView
  property_type: PropertyTypeView
  propose: ProposeView
  rank_notice: RankView
  recruit_notice: RecruitView
  refusal: RefusalView
  sanction_blocked: SanctionBlockedView
  sanctions: SanctionsView
  savings: SavingsView
  search: SearchView
  sell_offers: SellOffersView
  settings: SettingsView
  settlement_build_batch_confirm: LotBatchConfirmView
  settlement_build_confirm: LotConfirmView
  settlement_build_lots: LotGridView
  settlement_build_menu: BuildMenuView
  settlement_building_view: BuildingView
  settlement_construction_progress: ConstructionProgressView
  settlement_found_draft: FoundDraftView
  settlement_founded: SettlementFoundedView
  settlement_grid_grow: GridGrowView
  settlement_knowledge_list: KnowledgeListView
  settlement_land: LandView
  settlement_lot_access: LotAccessView
  settlement_lot_buy_confirm: LotBuyView
  settlement_lot_buy_done: LotBuyView
  settlement_lot_repair_done: LotRepairView
  settlement_mine: MineView
  settlement_private_confirm: PrivateConfirmView
  settlement_private_lots: PrivateLotsView
  settlement_private_menu: PrivateMenuView
  settlement_refusal: SettlementRefusalView
  settlement_terms: TermsView
  settlement_who: SettlementWhoView
  shop_bought: ShopBoughtView
  shop_checkout: ShopCheckoutView
  shop_detail: ShopView
  shop_refusal: ShopRefusalView
  shop_sold: ShopSoldView
  shops: ShopsView
  sleep_pay: SleepPayView
  stock: StockPageView
  stock_notice: StockView
  stock_order: StockOrderView
  stood: StoodView
  travel_arrived: TravelArrivedView
  travel_checkout: TravelCheckoutView
  travel_here: TravelHereView
  travel_options: TravelOptionsView
  travel_started: TravelStartedView
  travel_status: TravelStatusView
  treaties: TreatiesView
  treaty_proposed_notice: TreatyView
  victim_notice: VictimView
  village_donate_confirm: DonateView
  village_donate_done: DonateView
  village_donate_menu: DonateView
  village_home_call: EmptyView
  village_home_none: EmptyView
  village_materials: MaterialsView
  village_materials_buy_confirm: MaterialBuyView
  village_news: VillageNewsView
  village_overview: VillageOverviewView
  village_promote_confirm: PromotionView
  village_promoted: PromotionView
  village_promotion: PromotionView
  village_refusal: VillageRefusalView
  village_residence_confirm: ResidenceView
  village_residence_done: ResidenceView
  village_work: WorkView
  village_work_started: WorkView
  voted: VotedView
  walk_started: WalkStartedView
}

/** Screens whose response is a refusal: the answer carries an error code instead of ok. */
export const REFUSAL_SCREENS = ['appoint_refusal', 'auction_refusal', 'bill_refusal', 'diplomacy_refusal', 'election_refusal', 'faction_refusal', 'finance_refusal', 'founding_refusal', 'item_refusal', 'life_refusal', 'market_refusal', 'policy_refused', 'property_refusal', 'refusal', 'sanction_blocked', 'settlement_refusal', 'shop_refusal', 'village_refusal'] as const
