// GENERATED by cmd/contractgen from the Go view types (docs/adr/0039-presentation-split.md).
// Do not edit: change the Go view, run `go run ./cmd/contractgen > api/views.gen.ts`.
//
// Every field is always present. A nil pointer, slice or map, and a zero time, are null.
// A duration is whole seconds, rounded up, under the field's name with `_seconds` appended.

export interface AchievementView {
  achievement: Named
  cash: number
  withheld: number
}

export interface AllocationConfirmView {
  place: GovPlace
  lever: GovLever
  draft: string
  new: Record<string, number> | null
  vote_by: string
}

export interface AllocationEditView {
  place: GovPlace
  lever: GovLever
  draft: string
  lines: AllocationLine[] | null
  total: number
  spend_share_bps: number
  next_change_in_seconds: number
  changed: boolean
}

export interface AllocationLine {
  code: string
  share: number
  down: string
  up: string
}

export interface AppointDoneView {
  office: string
  place: GovPlace
  player: GovPlayer
  dismissed: boolean
  term_ends_in_seconds: number
}

export interface AppointRefusalView {
  kind: string
  gov: GovRefusal | null
  office: string
}

export interface AppointView {
  office: string
  place: GovPlace
  player: GovPlayer
}

export interface AuctionView {
  kind: string
  no: number
  item: Named
  amount: number
  fee: number
}

export interface BatchLotFailure {
  x: number
  y: number
  kind: string
}

export interface BillDecidedView {
  no: number
  place: Place
  subject: BillSubject
  body: string
  status: string
  lapsed_why: string
  yes: number
  nay: number
}

export interface BillRefusalView {
  kind: string
  no: number
  body: string
}

export interface BillSubject {
  kind: string
  code: string
  lever_type: string
  value: number
  allocation: Record<string, number> | null
  categories: string[] | null
  target: GovPlace | null
}

export interface BillView {
  no: number
  place: GovPlace
  subject: BillSubject
  office: string
  by: GovPlayer
  body: string
  rule: string
  threshold: string
  quorum: string
  seats: number
  held: number
  needs: number
  status: string
  lapsed_why: string
  yes: number
  nay: number
  votes: BillVoteLine[] | null
  closes_at: string | null
  remaining_seconds: number
  decided_ago_seconds: number
  can_vote: boolean
  notice: string
}

export interface BillVoteLine {
  player: GovPlayer
  yes: boolean
}

export interface BillsView {
  bills: BillView[] | null
}

export interface BoardLine {
  position: number
  code: string
  name: string
  tag: string
  tag_name: string
  city: Named
  value: number
  extra: number
  extra2: number
  mine: boolean
}

export interface BoardView {
  board: string
  lines: BoardLine[] | null
  at: string | null
  ranks: Record<string, Named> | null
}

export interface BuildLine {
  building: Named
  role: string
  state: string
  cost_money: number
  build_time_seconds: number
  missing: Named[] | null
  missing_buildings: Named[] | null
  materials: MaterialLine[] | null
  short: MaterialLine[] | null
}

export interface BuildMenuView {
  name: string
  treasury: number
  running_builds: number
  concurrent_cap: number
  lines: BuildLine[] | null
}

export interface BuildingEffectLine {
  target: string
  value: number
}

export interface BuildingResearchLine {
  knowledge: Named
  finish_at: string | null
  left_seconds: number
}

export interface BuildingStockLine {
  item: Named
  kind: string
  qty: number
}

export interface BuildingUpgradeLine {
  building: Named
  tier: number
  cost_money: number
  build_time_seconds: number
  available: boolean
  missing: Named[] | null
  needs_tier: string
}

export interface BuildingView {
  id: string
  building: Named
  role: string
  tier: number
  kind: string
  state: string
  mode: string
  x: number
  y: number
  w: number
  h: number
  rotated: boolean
  upkeep: number
  effects: BuildingEffectLine[] | null
  can_manage: boolean
  started_at: string | null
  finish_at: string | null
  left_seconds: number
  progress_percent: number
  stock: BuildingStockLine[] | null
  stock_used: number
  stock_capacity: number
  literacy_percent: number
  teaching: boolean
  treasury: number
  population: number
  research: BuildingResearchLine | null
  has_upgrade: boolean
  upgrades: BuildingUpgradeLine[] | null
}

export interface CandidateLine {
  player: GovPlayer
  mine: boolean
  votes: number
  counted: boolean
  elected: boolean
}

export interface CaseOutcomeView {
  crime: Named
  city_code: string
  city: string
  solved: boolean
  thief: string
  thief_code: string
  stolen: number
  restored: number
  shortfall: number
  fine: number
  fine_paid: number
  term_seconds: number
  returned: Named | null
}

export interface CityGovView {
  city: GovPlace
  sections: GovSection[] | null
  holds_office: boolean
  no_city: boolean
  tier: string
}

export interface ClinicTreatedView {
  ref: CompanyRef
  patient: string
  price: number
  item: Named
  units: number
  saved_seconds: number
}

export interface CompanyRef {
  code: string
  name: string
  type: Named
}

export interface ConstructionLine {
  id: string
  building: Named
  lot_x: number
  lot_y: number
  state: string
  finish_at: string | null
  left_seconds: number
  by_work: boolean
  progress_bps: number
  done_minutes: number
  required_minutes: number
  left_minutes: number
}

export interface ConstructionProgressView {
  name: string
  lines: ConstructionLine[] | null
  standing: StandingLine[] | null
}

export interface DiplomacyEntry {
  kind: string
  country: GovPlace
  other: GovPlace
  measures: string[] | null
  ground: string
  treaty: Named
  no: number
  by: GovPlayer | null
  office: string
  ago_seconds: number
}

export interface DiplomacyHistoryView {
  country: GovPlace
  entries: DiplomacyEntry[] | null
  page: number
  pages: number
}

export interface DiplomacyNotice {
  kind: string
  place: GovPlace
  treaty: Named
  in_seconds: number
}

export interface DiplomacyRefusalView {
  kind: string
  country: GovPlace
  office: string
  in_seconds: number
  back: Ref
}

export interface DismissView {
  office: string
  place: GovPlace
  seat: number
  holder: GovPlayer
}

export interface DonateView {
  village: string
  amount: number
  presets: number[] | null
  min: number
  max: number
  treasury: number
  cash: number
  settlement_id: string
}

export interface ElectionLine {
  no: number
  office: string
  place: GovPlace
  phase: string
  seats: number
  ends_at: string | null
  remaining_seconds: number
  candidates: number
  elected: GovPlayer[] | null
}

export interface ElectionRefusalView {
  kind: string
  no: number
  office: string
  place: GovPlace
}

export interface ElectionResultView {
  no: number
  office: string
  place: Place
  elected: boolean
  votes: number
  cast: number
  deposit: number
  deposit_returned: boolean
}

export interface ElectionView {
  no: number
  office: string
  place: GovPlace
  seats: number
  phase: string
  remaining_seconds: number
  candidacy_ends_at: string | null
  voting_ends_at: string | null
  votes_cast: number
  candidates: CandidateLine[] | null
  deposit: number
  refund_share_bps: number
  min_level: number
  standing: boolean
  voted: boolean
  can_stand: boolean
  can_vote: boolean
  stand_blocked: string
  vote_blocked: string
  payment: PaymentChoice | null
  nonce: string
}

export interface ElectionsView {
  no_city: boolean
  place: GovPlace
  elections: ElectionLine[] | null
}

export interface EmptyView {
}

export interface EndTreatyView {
  country: GovPlace
  treaty: TreatyLine
}

export interface FactionAnswerView {
  ref: FactionRef
  kind: string
  accepted: boolean
  player: Person
}

export interface FactionAnsweredView {
  ref: FactionRef
  kind: string
  accepted: boolean
  player: GovPlayer
}

export interface FactionAppliedView {
  ref: FactionRef
}

export interface FactionBankView {
  ref: FactionRef
  balance: number
  can_deposit: boolean
  can_withdraw: boolean
  cash: number
  bank_balance: number
  min: number
  max: number
  methods: string[] | null
  done: FactionMoneyDone | null
}

export interface FactionConfirmView {
  kind: string
  ref: FactionRef
  player: GovPlayer
}

export interface FactionCrimeBoardView {
  ref: FactionRef
  notice: string
  can_plan: boolean
  can_launch: boolean
  can_join: boolean
  cut_bps: number
  operation: FactionOperationLine | null
  in_crew: boolean
  crimes: FactionPlanLine[] | null
}

export interface FactionCrimeView {
  ref: FactionRef
  crime: Named
  result: string
  share: number
  take: number
  cut: number
  xp: number
  jail: Sentence | null
  fine: number
  fine_paid: number
  injury: Injury | null
}

export interface FactionFoundView {
  city_code: string
  city: string
  fee: number
  payment: PaymentChoice
  name_min: number
  name_max: number
}

export interface FactionFoundedView {
  ref: FactionRef
  city_code: string
  city: string
  fee: number
  method: string
}

export interface FactionHomeView {
  ref: FactionRef
  rank: string
  linked: boolean
  rights: string[] | null
  city_code: string
  city: string
  members: number
  max_members: number
  bank: number
  applications: number
  operation: FactionOperationLine | null
}

export interface FactionInvitedView {
  player: GovPlayer
}

export interface FactionLeftView {
  ref: FactionRef
  disbanded: boolean
  paid_out: number
}

export interface FactionLine {
  ref: FactionRef
  members: number
}

export interface FactionLinkedView {
  ref: FactionRef
}

export interface FactionListView {
  city_code: string
  city: string
  fee: number
  factions: FactionLine[] | null
  mine: FactionRef | null
}

export interface FactionMemberLine {
  player: GovPlayer
  rank: string
  self: boolean
  can_kick: boolean
  can_promote: boolean
  can_demote: boolean
  can_lead: boolean
}

export interface FactionMembersView {
  ref: FactionRef
  max: number
  can_invite: boolean
  members: FactionMemberLine[] | null
  requests: FactionRequestLine[] | null
}

export interface FactionMoneyDone {
  deposit: boolean
  amount: number
  method: string
}

export interface FactionOperationLine {
  no: number
  status: string
  crime: Named
  place: Named
  city_code: string
  city: string
  chance_bps: number
  min: number
  max: number
  nerve: number
  crew: FactionMemberLine[] | null
  left_seconds: number
  at: string | null
  expired: boolean
}

export interface FactionPageView {
  ref: FactionRef
  city_code: string
  city: string
  linked: boolean
  members: FactionMemberLine[] | null
  mine: boolean
  can_apply: boolean
  can_link: boolean
}

export interface FactionPlanLine {
  crime: Named
  min: number
  max: number
  nerve: number
  min_level: number
  duration_seconds: number
  places: Named[] | null
}

export interface FactionRef {
  code: string
  name: string
}

export interface FactionRefusalView {
  kind: string
  min: number
  max: number
  amount: number
  balance: number
  need: number
  have: number
  level: number
}

export interface FactionRequestLine {
  no: number
  kind: string
  player: GovPlayer
  can_decide: boolean
}

export interface FactionRequestView {
  no: number
  kind: string
  ref: FactionRef
  player: Person
}

export interface FinanceView {
  kind: string
  no: number
  product: Named
  amount: number
  other: number
  count: number
  at: string | null
  pledge: Pledge | null
}

export interface FoundDraftView {
  founder: string
  pending: boolean
  minutes: number
  draft_id: string
}

export interface FoundingCheckedView {
  name: string
  currency_code: string
}

export interface FoundingChoiceView {
  code: string
  hex: string
}

export interface FoundingEmblemView {
  shape: string
  color_a: string
  color_b: string
  icon: string
}

export interface FoundingFormView {
  state: string
  draft: string
  expires_at: string | null
  founder: string
  suggested_name: string
  default_emblem: FoundingEmblemView
  limits: FoundingLimitsView
  shapes: FoundingChoiceView[] | null
  palette: FoundingChoiceView[] | null
  icons: FoundingChoiceView[] | null
  neutral_currency: string
  settlement_id: string
  settlement_name: string
}

export interface FoundingLimitsView {
  name_min: number
  name_max: number
  motto_max: number
  currency_name_min: number
  currency_name_max: number
  currency_code_len: number
  currency_symbol_max: number
}

export interface FoundingProblem {
  field: string
  code: string
}

export interface FoundingRefusalView {
  kind: string
  problems: FoundingProblem[] | null
  name: string
  limits: FoundingLimitsView
}

export interface FriendAcceptedView {
  name: string
}

export interface FriendLine {
  id: string
  name: string
  status: string
  incoming: boolean
}

export interface FriendRequestedView {
  name: string
}

export interface FriendsView {
  friends: FriendLine[] | null
  page: number
  pages: number
}

export interface GovAppointee {
  office: string
  place: GovPlace
  seat: number
  holder: GovPlayer | null
  can_appoint: boolean
  can_dismiss: boolean
}

export interface GovHistoryEntry {
  place: GovPlace
  lever: string
  type: string
  office: string
  by: GovPlayer | null
  old: number
  new: number
  ago_seconds: number
  effective_in_seconds: number
}

export interface GovHistoryView {
  city: GovPlace
  entries: GovHistoryEntry[] | null
  page: number
  pages: number
}

export interface GovLever {
  code: string
  type: string
  value: number
  default: number
  min: number
  max: number
  from_office: boolean
  set_by: GovPlayer | null
  pending: GovPending | null
  held_by: string
  notice_seconds: number
  cooldown_seconds: number
  vote: boolean
  confirm_by: string
  allocation: Record<string, number> | null
  categories: string[] | null
}

export interface GovOffice {
  code: string
  seats: number
  holders: GovPlayer[] | null
  acting_code: string
  acting: GovPlayer[] | null
}

export interface GovPending {
  value: number
  allocation: Record<string, number> | null
  in_seconds: number
  by: GovPlayer | null
}

export interface GovPlace {
  kind: string
  code: string
  name: string
}

export interface GovPlayer {
  name: string
  code: string
}

export interface GovRefusal {
  kind: string
  office: string
  wait_seconds: number
}

export interface GovSeat {
  office: string
  place: GovPlace
  acting_for: string
  levers: GovLever[] | null
  vote_levers: GovLever[] | null
  appointees: GovAppointee[] | null
}

export interface GovSection {
  place: GovPlace
  offices: GovOffice[] | null
  levers: GovLever[] | null
}

export interface GridGrowView {
  settlement_name: string
  side: number
  new_side: number
  lots_gained: number
  buildable_gained: number
  price: number
  treasury: number
}

export interface HospitalisedView {
  city_code: string
  city: string
  cause: string
  damage: number
  health: number
  max: number
  ends_at: string | null
  remaining_seconds: number
}

export interface ImposeView {
  country: GovPlace
  targets: GovPlace[] | null
  target: GovPlace | null
  mask: number
  measures: MeasureToggle[] | null
  chosen: string[] | null
  grounds: string[] | null
  ground: string
  notice_seconds: number
  min_duration_seconds: number
}

export interface InboxBadgeView {
  unread: number
  categories: InboxCategoryCount[] | null
  teaser: StoredNotice[] | null
}

export interface InboxCategoryCount {
  category: string
  count: number
}

export interface InboxCategoryView {
  category: string
  items: InboxItemLine[] | null
  page: number
  total_pages: number
}

export interface InboxHubCategory {
  category: string
  count: number
}

export interface InboxHubView {
  total: number
  categories: InboxHubCategory[] | null
}

export interface InboxItemLine {
  kind: string
  notice: StoredNotice
  ago_seconds: number
  link: Ref
}

export interface InboxReminderView {
  unread: number
}

export interface Injury {
  damage: number
  health: number
  max: number
  hospital: boolean
  ends_at: string | null
}

export interface KnowledgeLine {
  knowledge: Named
  state: string
  research_cost: number
  research_time_seconds: number
  buy_price: number
  missing: Named[] | null
  terrain_ok: boolean
}

export interface KnowledgeListView {
  name: string
  treasury: number
  literacy_percent: number
  running: KnowledgeResearchLine | null
  lines: KnowledgeLine[] | null
  hidden: number
}

export interface KnowledgeResearchLine {
  knowledge: Named
  finish_at: string | null
  left_seconds: number
}

export interface LaborBoardView {
  village: string
  jobs: LaborJobLine[] | null
  market: LaborMarketLine
  working: LaborShiftLine | null
  resident: boolean
  sites: LaborSiteRef[] | null
}

export interface LaborJobLine {
  id: string
  building_id: string
  building: Named
  kind: string
  employer_kind: string
  employer: string
  wage: number
  left: number
  total: number
  progress_bps: number
  left_minutes: number
  workers: number
  npc_crew: number
  can_take: boolean
  mine: boolean
  points: number
}

export interface LaborMarketLine {
  housing: number
  pool: number
  available: number
  working: number
  vacancies: number
  tightness_bps: number
  level: string
  npc_wage: number
  min_wage: number
}

export interface LaborMineView {
  village: string
  shifts: number
  earned: number
  level: string
  productivity_bps: number
  next_level: string
  next_shifts: number
  working: LaborShiftLine | null
  market: LaborMarketLine
}

export interface LaborPreset {
  percent: number
  wage: number
}

export interface LaborShiftLine {
  id: string
  building: Named
  kind: string
  worker: string
  worker_npc: boolean
  level: string
  finish_at: string | null
  left_seconds: number
  wage: number
  points: number
}

export interface LaborSiteRef {
  id: string
  building: Named
  progress_bps: number
}

export interface LaborSiteView {
  village: string
  building: Named
  id: string
  status: string
  progress_bps: number
  required_minutes: number
  done_minutes: number
  left_minutes: number
  job: LaborJobLine | null
  workers: LaborShiftLine[] | null
  market: LaborMarketLine
  can_work: boolean
  work_wage: number
  work_points: number
  working: LaborShiftLine | null
  can_employ: boolean
  can_post: boolean
  hire_presets: number[] | null
  wage_presets: LaborPreset[] | null
  npc_available: number
  npc_wage: number
  just: string
}

export interface LandCell {
  x: number
  y: number
  state: string
  owner: string
  building: string
}

export interface LandView {
  village: string
  settlement_id: string
  grid_lots: number
  rows: (LandCell[] | null)[] | null
  price: number
  cash: number
  owned: number
  max: number
  can_buy: boolean
  free_lots: number
}

export interface LeverEditView {
  place: GovPlace
  lever: GovLever
  draft: number
  fine_step: number
  coarse_step: number
  next_change_in_seconds: number
}

export interface LiftView {
  country: GovPlace
  sanction: SanctionLine
}

export interface Loot {
  item: Named
  qty: number
}

export interface LotBatchConfirmView {
  settlement_name: string
  building: Named
  lots: LotBatchLot[] | null
  count: number
  cost_money: number
  materials: MaterialLine[] | null
  build_time_seconds: number
}

export interface LotBatchLot {
  x: number
  y: number
}

export interface LotBuyView {
  village: string
  settlement_id: string
  x: number
  y: number
  price: number
  cash: number
  treasury: number
}

export interface LotCell {
  x: number
  y: number
  state: string
  own: boolean
  fits: boolean
}

export interface LotConfirmView {
  settlement_name: string
  building: Named
  x: number
  y: number
  rotated: boolean
  cost_money: number
  materials: MaterialLine[] | null
  build_time_seconds: number
  auto_roads: number
}

export interface LotGridView {
  settlement_name: string
  building: Named
  can_rotate: boolean
  rotated: boolean
  grid_lots: number
  rows: (LotCell[] | null)[] | null
  multi: boolean
  line: string
  from: LotBatchLot
  win_x: number
  win_y: number
}

export interface MarketFilledView {
  side: string
  item: Named
  qty: number
  price: number
  amount: number
  fee: number
  city_code: string
  city: string
}

export interface MaterialBought {
  item: Named
  qty: number
  total: number
}

export interface MaterialBuyView {
  village: string
  item: Named
  qty: number
  unit: number
  total: number
  treasury: number
  free: number
}

export interface MaterialLine {
  component: Named
  quantity: number
}

export interface MaterialMarketLine {
  item: Named
  price: number
}

export interface MaterialStockLine {
  item: Named
  qty: number
}

export interface MaterialsView {
  village: string
  treasury: number
  stock: MaterialStockLine[] | null
  used: number
  capacity: number
  market: MaterialMarketLine[] | null
  can_buy: boolean
  presets: number[] | null
  bought: MaterialBought | null
}

export interface MeasureToggle {
  code: string
  on: boolean
  mask: number
}

export interface MineLot {
  x: number
  y: number
  building: string
  state: string
  finish_at: string | null
  left_seconds: number
}

export interface MineView {
  village: string
  settlement_id: string
  cash: number
  lots: MineLot[] | null
  home: Named | null
  can_rest: boolean
  rest_wait_seconds: number
  assessed: number
  tax_per_period: number
  tax_bps: number
  debt: number
  debt_periods: number
  notice: string
}

export interface MissionCompletedView {
  mission: Named
  cash: number
  withheld: number
  xp: number
  items: Loot[] | null
}

export interface MyOfficeView {
  seats: GovSeat[] | null
}

export interface Named {
  code: string
  name: string
}

export interface OfficeView {
  office: string
  place: Place
  by: Person
  by_office: string
  dismissed: boolean
}

export interface PaymentChoice {
  amount: number
  accepted: string[] | null
  usable: string[] | null
  cash: number
  bank: number
}

export interface PaymentView {
  payer_name: string
  payer_code: string
  method: string
  amount: number
}

export interface Person {
  name: string
  code: string
}

export interface Place {
  kind: string
  code: string
  name: string
}

export interface Pledge {
  no: number
  code: string
  type: Named
  city: Place
  value: number
  limit: number
}

export interface PolicyAnnouncedView {
  place: GovPlace
  lever: GovLever
  old: number
  new: number
  old_allocation: Record<string, number> | null
  new_allocation: Record<string, number> | null
  in_seconds: number
}

export interface PolicyConfirmView {
  place: GovPlace
  lever: GovLever
  new_value: number
  vote_by: string
}

export interface PolicyRefusalView {
  refusal: GovRefusal
  place: GovPlace | null
  lever: GovLever | null
}

export interface PrivateConfirmView {
  village: string
  building: Named
  x: number
  y: number
  rotated: boolean
  cost_money: number
  permit_fee: number
  materials: PrivateMaterial[] | null
  materials_cost: number
  total: number
  cash: number
  build_time_seconds: number
}

export interface PrivateLine {
  building: Named
  home: boolean
  class: string
  cost_money: number
  permit_fee: number
  materials: PrivateMaterial[] | null
  build_time_seconds: number
  footprint_w: number
  footprint_h: number
  total: number
  affordable: boolean
}

export interface PrivateLotsView {
  village: string
  building: Named
  can_rotate: boolean
  rotated: boolean
  grid_lots: number
  rows: (LotCell[] | null)[] | null
}

export interface PrivateMaterial {
  component: Named
  need: number
  have: number
  buy: number
  buy_cost: number
}

export interface PrivateMenuView {
  village: string
  settlement_id: string
  cash: number
  owned_lots: number
  free_lots: number
  lines: PrivateLine[] | null
}

export interface PromotionCriterionView {
  kind: string
  role: string
  current: number
  required: number
  met: boolean
}

export interface PromotionView {
  village: string
  from: string
  to: string
  criteria: PromotionCriterionView[] | null
  met: boolean
  can_promote: boolean
  office: string
  settlement_id: string
}

export interface PropertyView {
  kind: string
  type: Named
  no: number
  city: Place
  player: Person
  amount: number
}

export interface ProposeView {
  country: GovPlace
  partners: GovPlace[] | null
  partner: GovPlace | null
  kinds: Named[] | null
  kind: Named | null
  ttl_seconds: number
}

export interface Rank {
  code: string
  name: string
  emoji: string
}

export interface RankView {
  rank: Rank
  from: Rank
  up: boolean
  worth: number
}

export interface RecruitView {
  kind: string
  company: CompanyRef
  campaign_no: number
  count: number
  name_seed: number
  skill: string
  level: number
  reason: string
  amount: number
}

export interface Ref {
  command: string
  args: string[] | null
}

export interface ResidenceView {
  leaving: boolean
  village: string
  home: string
  home_code: string
  cooldown_seconds: number
  population: number
  settlement_id: string
}

export interface SanctionBlockedView {
  measure: string
  imposer: GovPlace
  target: GovPlace
  back: Ref
}

export interface SanctionLine {
  no: number
  imposer: GovPlace
  target: GovPlace
  measures: string[] | null
  ground: string
  by: GovPlayer | null
  office: string
  since_seconds: number
  in_force_in_seconds: number
  liftable: boolean
  liftable_in_seconds: number
}

export interface SanctionsView {
  country: GovPlace
  imposed: SanctionLine[] | null
  suffered: SanctionLine[] | null
  can_impose: boolean
  notice: DiplomacyNotice | null
}

export interface SearchResult {
  id: string
  name: string
  code: string
  self: boolean
}

export interface SearchView {
  help: boolean
  by: string
  query: string
  found: SearchResult | null
}

export interface Sentence {
  crime: Named
  remaining_seconds: number
  ends_at: string | null
}

export interface SettlementFoundedView {
  name: string
  settlement_id: string
  biome_code: string
  nearby_feature: string
  buildings: string[] | null
  protected_until: string | null
  founder: string
  emblem: FoundingEmblemView
  motto: string
  currency_name: string
  currency_code: string
  currency_symbol: string
}

export interface SettlementRefusalView {
  kind: string
  name: string
}

export interface SettlementWhoView {
  name: string
  online: WhoLine[] | null
  offline: number
}

export interface StandingLine {
  id: string
  building: Named
  lot_x: number
  lot_y: number
}

export interface StockView {
  kind: string
  company: Named
  side: string
  qty: number
  price: number
  amount: number
  player: string
}

export interface StoodView {
  no: number
  office: string
  place: GovPlace
  deposit: number
  method: string
  voting_at: string | null
  voting_in_seconds: number
}

export interface StoredNotice {
  screen: string
  view: unknown
  text: string
}

export interface TermsView {
  village: string
  settlement_id: string
  lot_price: number
  lot_price_min: number
  lot_price_max: number
  permit_fee: number
  permit_fee_max: number
  tax_bps: number
  tax_bps_max: number
  lot_presets: number[] | null
  permit_presets: number[] | null
  tax_presets: number[] | null
  default_lot_price: number
  default_permit: number
  default_tax_bps: number
}

export interface TreatiesView {
  country: GovPlace
  treaties: TreatyLine[] | null
  can_act: boolean
  notice: DiplomacyNotice | null
}

export interface TreatyLine {
  no: number
  kind: Named
  other: GovPlace
  status: string
  incoming: boolean
  expires_in_seconds: number
  since_seconds: number
}

export interface TreatyView {
  country: Place
  other: Place
  kind: Named
  no: number
  ttl_seconds: number
}

export interface VictimView {
  crime: Named
  venue: Named
  city_code: string
  city: string
  amount: number
  thief_name: string
  thief_code: string
  crime_id: string
  report_fee: number
  report_within_seconds: number
  item: Named | null
}

export interface VillageMaker {
  building: Named
  built: boolean
}

export interface VillageNeed {
  kind: string
  item: Named
  options: Named[] | null
  have: number
  need: number
  makers: VillageMaker[] | null
  price: number
}

export interface VillageNewsItem {
  kind: string
  building: Named
  knowledge: Named
  percent: number
  player: string
  amount: number
  tier: string
}

export interface VillageNewsView {
  village: string
  items: VillageNewsItem[] | null
}

export interface VillageOverviewView {
  name: string
  tier: string
  population: number
  population_cap: number
  food_percent: number
  job_percent: number
  service_percent: number
  happiness_percent: number
  security_percent: number
  literacy_percent: number
  resident: boolean
  settlement_id: string
  treasury: number
  buildings: VillageRoleLine[] | null
  is_head: boolean
  support: VillageSupport | null
  promotion: PromotionView | null
}

export interface VillageRefusalView {
  kind: string
  back: Ref
  remaining_seconds: number
  min: number
  max: number
  lots: BatchLotFailure[] | null
  action: string
  subject: Named
  needs: VillageNeed[] | null
}

export interface VillageRoleLine {
  role: string
  building: Named
  tier: number
}

export interface VillageSupport {
  code: string
  name: string
}

export interface VotedView {
  no: number
  office: string
  place: GovPlace
  candidate: GovPlayer
  count_at: string | null
  count_in_seconds: number
}

export interface WhoLine {
  name: string
  activity: string
  place: string
}

export interface WorkShiftLine {
  building: Named
  finish_at: string | null
  left_seconds: number
  wage: number
  produces: MaterialLine[] | null
}

export interface WorkView {
  village: string
  resident: boolean
  places: WorkplaceLine[] | null
  mine: WorkShiftLine | null
  suggest: Named[] | null
  started: boolean
  used: number
  capacity: number
}

export interface WorkplaceLine {
  id: string
  building: Named
  produces: MaterialLine[] | null
  consumes: MaterialLine[] | null
  wage: number
  shift_seconds: number
  workers: number
  busy: number
  ready: boolean
}

/** The screens of the migrated areas: the screen name on the wire, and its view. */
export interface ScreenViews {
  achievement_notice: AchievementView
  allocation_confirm: AllocationConfirmView
  allocation_edit: AllocationEditView
  appoint_confirm: AppointView
  appoint_done: AppointDoneView
  appoint_refusal: AppointRefusalView
  auction_notice: AuctionView
  bill: BillView
  bill_decided_notice: BillDecidedView
  bill_refusal: BillRefusalView
  bills: BillsView
  case_solved_notice: CaseOutcomeView
  city_governance: CityGovView
  clinic_treated_notice: ClinicTreatedView
  convicted_notice: CaseOutcomeView
  diplomacy_history: DiplomacyHistoryView
  diplomacy_refusal: DiplomacyRefusalView
  dismiss_confirm: DismissView
  election: ElectionView
  election_refusal: ElectionRefusalView
  election_result_notice: ElectionResultView
  elections: ElectionsView
  end_treaty: EndTreatyView
  faction_answer_notice: FactionAnswerView
  faction_answered: FactionAnsweredView
  faction_applied: FactionAppliedView
  faction_bank: FactionBankView
  faction_confirm: FactionConfirmView
  faction_crime: FactionCrimeBoardView
  faction_crime_notice: FactionCrimeView
  faction_found: FactionFoundView
  faction_founded: FactionFoundedView
  faction_home: FactionHomeView
  faction_invited: FactionInvitedView
  faction_left: FactionLeftView
  faction_linked: FactionLinkedView
  faction_list: FactionListView
  faction_members: FactionMembersView
  faction_page: FactionPageView
  faction_refusal: FactionRefusalView
  faction_request_notice: FactionRequestView
  finance_notice: FinanceView
  founding_checked: FoundingCheckedView
  founding_form: FoundingFormView
  founding_refusal: FoundingRefusalView
  friend_accepted: FriendAcceptedView
  friend_requested: FriendRequestedView
  friends: FriendsView
  gov_history: GovHistoryView
  hospitalised_notice: HospitalisedView
  hunger_notice: EmptyView
  impose: ImposeView
  inbox_badge: InboxBadgeView
  inbox_category: InboxCategoryView
  inbox_hub: InboxHubView
  inbox_reminder: InboxReminderView
  labor_board: LaborBoardView
  labor_mine: LaborMineView
  labor_site: LaborSiteView
  leaderboard: BoardView
  lever_edit: LeverEditView
  lift: LiftView
  market_filled_notice: MarketFilledView
  mission_completed_notice: MissionCompletedView
  my_office: MyOfficeView
  office_notice: OfficeView
  payment_notice: PaymentView
  policy_announced: PolicyAnnouncedView
  policy_confirm: PolicyConfirmView
  policy_refused: PolicyRefusalView
  property_notice: PropertyView
  propose: ProposeView
  rank_notice: RankView
  recruit_notice: RecruitView
  sanction_blocked: SanctionBlockedView
  sanctions: SanctionsView
  search: SearchView
  settlement_build_batch_confirm: LotBatchConfirmView
  settlement_build_confirm: LotConfirmView
  settlement_build_lots: LotGridView
  settlement_build_menu: BuildMenuView
  settlement_building_view: BuildingView
  settlement_construction_progress: ConstructionProgressView
  settlement_found_draft: FoundDraftView
  settlement_founded: SettlementFoundedView
  settlement_grid_grow: GridGrowView
  settlement_knowledge_list: KnowledgeListView
  settlement_land: LandView
  settlement_lot_buy_confirm: LotBuyView
  settlement_lot_buy_done: LotBuyView
  settlement_mine: MineView
  settlement_private_confirm: PrivateConfirmView
  settlement_private_lots: PrivateLotsView
  settlement_private_menu: PrivateMenuView
  settlement_refusal: SettlementRefusalView
  settlement_terms: TermsView
  settlement_who: SettlementWhoView
  stock_notice: StockView
  stood: StoodView
  treaties: TreatiesView
  treaty_proposed_notice: TreatyView
  victim_notice: VictimView
  village_donate_confirm: DonateView
  village_donate_done: DonateView
  village_donate_menu: DonateView
  village_home_call: EmptyView
  village_home_none: EmptyView
  village_materials: MaterialsView
  village_materials_buy_confirm: MaterialBuyView
  village_news: VillageNewsView
  village_overview: VillageOverviewView
  village_promote_confirm: PromotionView
  village_promoted: PromotionView
  village_promotion: PromotionView
  village_refusal: VillageRefusalView
  village_residence_confirm: ResidenceView
  village_residence_done: ResidenceView
  village_work: WorkView
  village_work_started: WorkView
  voted: VotedView
}

/** Screens whose response is a refusal: the answer carries an error code instead of ok. */
export const REFUSAL_SCREENS = ['appoint_refusal', 'bill_refusal', 'diplomacy_refusal', 'election_refusal', 'faction_refusal', 'founding_refusal', 'policy_refused', 'sanction_blocked', 'settlement_refusal', 'village_refusal'] as const
