// GENERATED by cmd/contractgen from the Go view types (docs/adr/0039-presentation-split.md).
// Do not edit: change the Go view, run `go run ./cmd/contractgen > api/views.gen.ts`.
//
// Every field is always present. A nil pointer, slice or map, and a zero time, are null.
// A duration is whole seconds, rounded up, under the field's name with `_seconds` appended.

export interface AmountOption {
  amount: number
  nonce: string
  all: boolean
}

export interface AuctionLine {
  no: number
  item: Named
  quality: number
  high_bid: number
  reserve: number
  remaining_seconds: number
  ends_at: string | null
  status: string
  mine: boolean
  leading: boolean
}

export interface AuctionNewView {
  item: Named
  ref: string
  quality: number
  reserves: number[] | null
  durations: number[] | null
  nonce: string
}

export interface AuctionOpenedView {
  no: number
  item: Named
  reserve: number
  duration_seconds: number
  ends_at: string | null
}

export interface AuctionRefusalView {
  kind: string
  no: number
  min_next: number
  count: number
}

export interface AuctionView {
  line: AuctionLine
  min_next: number
  bids: number
  payment: PaymentChoice | null
  nonce: string
  seller: string
}

export interface AuctionsView {
  city_code: string
  city: string
  auctions: AuctionLine[] | null
  at_house: boolean
  way: Way | null
  unavailable: Unavailable | null
}

export interface BankView {
  city_code: string
  city: string
  travelling: boolean
  no_city: boolean
  jailed: boolean
  cash: number
  bank: number
  withdrawal_fee_bps: number
  deposits: AmountOption[] | null
  withdrawals: AmountOption[] | null
  can_deposit: boolean
  can_withdraw: boolean
  notice: string
  notice_args: Record<string, unknown> | null
}

export interface BatchLotFailure {
  x: number
  y: number
  kind: string
}

export interface BidPlacedView {
  no: number
  item: Named
  amount: number
  method: string
  ends_at: string | null
}

export interface BookLevel {
  price: number
  qty: number
}

export interface BookSummary {
  item: Named
  best_bid: number
  best_ask: number
  last: number
}

export interface BookView {
  item: Named
  city_code: string
  city: string
  bids: BookLevel[] | null
  asks: BookLevel[] | null
  trades: TradeLine[] | null
  reference: number
  holding: number
  at_market: boolean
  way: Way | null
  nonce: string
}

export interface BudgetLineView {
  code: string
  effect: string
  spent: number
  effect_bps: number
}

export interface BudgetPeriodView {
  spent: number
  spendable: number
  lines: BudgetLineView[] | null
}

export interface BudgetView {
  no_city: boolean
  city: GovPlace
  lever: string
  can_propose: boolean
  spend_share_bps: number
  order: string[] | null
  allocation: Record<string, number> | null
  pending: Record<string, number> | null
  pending_in_seconds: number
  treasury: number
  last: BudgetPeriodView | null
  next_at: string | null
  next_in_seconds: number
}

export interface BuildLine {
  building: Named
  role: string
  state: string
  cost_money: number
  build_time_seconds: number
  missing: Named[] | null
  missing_buildings: Named[] | null
  materials: MaterialLine[] | null
  short: MaterialLine[] | null
}

export interface BuildMenuView {
  name: string
  treasury: number
  running_builds: number
  concurrent_cap: number
  lines: BuildLine[] | null
}

export interface BuildingEffectLine {
  target: string
  value: number
}

export interface BuildingResearchLine {
  knowledge: Named
  finish_at: string | null
  left_seconds: number
}

export interface BuildingStockLine {
  item: Named
  kind: string
  qty: number
}

export interface BuildingUpgradeLine {
  building: Named
  tier: number
  cost_money: number
  build_time_seconds: number
  available: boolean
  missing: Named[] | null
  needs_tier: string
}

export interface BuildingView {
  id: string
  building: Named
  role: string
  tier: number
  kind: string
  state: string
  mode: string
  x: number
  y: number
  w: number
  h: number
  rotated: boolean
  upkeep: number
  effects: BuildingEffectLine[] | null
  can_manage: boolean
  started_at: string | null
  finish_at: string | null
  left_seconds: number
  progress_percent: number
  stock: BuildingStockLine[] | null
  stock_used: number
  stock_capacity: number
  literacy_percent: number
  teaching: boolean
  treasury: number
  population: number
  research: BuildingResearchLine | null
  has_upgrade: boolean
  upgrades: BuildingUpgradeLine[] | null
}

export interface ConstructionLine {
  id: string
  building: Named
  lot_x: number
  lot_y: number
  state: string
  finish_at: string | null
  left_seconds: number
  by_work: boolean
  progress_bps: number
  done_minutes: number
  required_minutes: number
  left_minutes: number
}

export interface ConstructionProgressView {
  name: string
  lines: ConstructionLine[] | null
  standing: StandingLine[] | null
}

export interface CreditView {
  score: number
  min: number
  max: number
  payment_bps: number
  debt_bps: number
  history_bps: number
  income_bps: number
  worth_bps: number
  new_credit_bps: number
  missed: number
  defaults: number
}

export interface DividendView {
  company: Named
  free: number
  tax_bps: number
  total: number
  options: PriceOption[] | null
  chosen: PriceOption | null
  nonce: string
  paid: number
  per_share: number
  holders: number
  refused: string
}

export interface DonateView {
  village: string
  amount: number
  presets: number[] | null
  min: number
  max: number
  treasury: number
  cash: number
  settlement_id: string
}

export interface EmptyView {
}

export interface ExchangeView {
  lines: ListedLine[] | null
  unavailable: Unavailable | null
}

export interface FinanceHubView {
  country: GovPlace
  credit: CreditView
  policy_bps: number
  products: LoanProductLine[] | null
  loans: LoanLine[] | null
  savings: number
  savings_bps: number
  lendable: number
  next_at: string | null
  notice: string
  args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface FinanceRefusalView {
  kind: string
  amount: number
  score: number
  count: number
  wait_seconds: number
  back: Ref
}

export interface GoldPoint {
  price: number
  at: string | null
}

export interface GoldTradeView {
  side: string
  grams: number
  price: number
  total: number
  payment: PaymentChoice
  nonce: string
}

export interface GoldView {
  buy: number
  sell: number
  mid: number
  prev: number
  stock: number
  history: GoldPoint[] | null
  grams: number
  cost: number
  options: number[] | null
  next_at: string | null
  notice: string
  notice_args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface GovPlace {
  kind: string
  code: string
  name: string
}

export interface GridGrowView {
  settlement_name: string
  side: number
  new_side: number
  lots_gained: number
  buildable_gained: number
  price: number
  treasury: number
}

export interface HoldingLine {
  company: Named
  shares: number
  locked: number
  price: number
  value: number
  cost: number
  listed: boolean
}

export interface InsuranceProductLine {
  product: Named
  covers: string
  premium: number
  prem_bps: number
  cover_bps: number
  max_claim: number
  waiting_seconds: number
  targets: PledgeLine[] | null
  held: boolean
}

export interface InsuranceView {
  country: GovPlace
  fund: number
  products: InsuranceProductLine[] | null
  policies: PolicyLine[] | null
  notice: string
  notice_args: Record<string, unknown> | null
  cancel: PolicyLine | null
  unavailable: Unavailable | null
}

export interface InsureConfirmView {
  product: Named
  covers: string
  property: PledgeLine | null
  premium: number
  cover_bps: number
  max_claim: number
  waiting_seconds: number
  payment: PaymentChoice
}

export interface KnowledgeLine {
  knowledge: Named
  state: string
  research_cost: number
  research_time_seconds: number
  buy_price: number
  missing: Named[] | null
  terrain_ok: boolean
}

export interface KnowledgeListView {
  name: string
  treasury: number
  literacy_percent: number
  running: KnowledgeResearchLine | null
  lines: KnowledgeLine[] | null
  hidden: number
}

export interface KnowledgeResearchLine {
  knowledge: Named
  finish_at: string | null
  left_seconds: number
}

export interface LaborBoardView {
  village: string
  jobs: LaborJobLine[] | null
  market: LaborMarketLine
  working: LaborShiftLine | null
  resident: boolean
  sites: LaborSiteRef[] | null
}

export interface LaborJobLine {
  id: string
  building_id: string
  building: Named
  kind: string
  employer_kind: string
  employer: string
  wage: number
  left: number
  total: number
  progress_bps: number
  left_minutes: number
  workers: number
  npc_crew: number
  can_take: boolean
  mine: boolean
  points: number
}

export interface LaborMarketLine {
  housing: number
  pool: number
  available: number
  working: number
  vacancies: number
  tightness_bps: number
  level: string
  npc_wage: number
  min_wage: number
}

export interface LaborMineView {
  village: string
  shifts: number
  earned: number
  level: string
  productivity_bps: number
  next_level: string
  next_shifts: number
  working: LaborShiftLine | null
  market: LaborMarketLine
}

export interface LaborPreset {
  percent: number
  wage: number
}

export interface LaborShiftLine {
  id: string
  building: Named
  kind: string
  worker: string
  worker_npc: boolean
  level: string
  finish_at: string | null
  left_seconds: number
  wage: number
  points: number
}

export interface LaborSiteRef {
  id: string
  building: Named
  progress_bps: number
}

export interface LaborSiteView {
  village: string
  building: Named
  id: string
  status: string
  progress_bps: number
  required_minutes: number
  done_minutes: number
  left_minutes: number
  job: LaborJobLine | null
  workers: LaborShiftLine[] | null
  market: LaborMarketLine
  can_work: boolean
  work_wage: number
  work_points: number
  working: LaborShiftLine | null
  can_employ: boolean
  can_post: boolean
  hire_presets: number[] | null
  wage_presets: LaborPreset[] | null
  npc_available: number
  npc_wage: number
  just: string
}

export interface LandCell {
  x: number
  y: number
  state: string
  owner: string
  building: string
}

export interface LandView {
  village: string
  settlement_id: string
  grid_lots: number
  rows: (LandCell[] | null)[] | null
  price: number
  cash: number
  owned: number
  max: number
  can_buy: boolean
  free_lots: number
}

export interface ListedLine {
  company: Named
  type: Named
  city: GovPlace
  price: number
  prev: number
  volume: number
  cap: number
}

export interface ListingView {
  company: Named
  refused: string
  age_seconds: number
  min_age_seconds: number
  revenue: number
  min_revenue: number
  book: number
  total: number
  fee: number
  floats: PriceOption[] | null
  prices: PriceOption[] | null
  chosen: PriceOption | null
  nonce: string
}

export interface LoanConfirmView {
  product: Named
  amount: number
  term: number
  rate_bps: number
  interest: number
  instalment: number
  total: number
  first_at: string | null
  pledge: PledgeLine | null
  nonce: string
}

export interface LoanDetailView {
  loan: LoanLine
  principal: number
  interest: number
  rate_bps: number
  periods: number
  paid: number
  fees_due: number
  payoff: number
  pledge: PledgeLine | null
  opened_at: string | null
  next_at: string | null
  missed: number
  recovered: number
  written_off: number
  nonce: string
  notice: string
  notice_args: Record<string, unknown> | null
  confirm_open: boolean
}

export interface LoanLine {
  no: number
  product: Named
  company: Named
  status: string
  next: number
  owed: number
  left: number
  arrears: number
}

export interface LoanOfferView {
  product: Named
  kind: string
  rate_bps: number
  limit: number
  terms: number[] | null
  options: LoanOption[] | null
  pledges: PledgeLine[] | null
  pledge: PledgeLine | null
  late_fee_bps: number
  default_after: number
  unavailable: Unavailable | null
}

export interface LoanOption {
  amount: number
  term: number
  instalment: number
}

export interface LoanProductLine {
  product: Named
  kind: string
  rate_bps: number
  limit: number
  min_score: number
}

export interface LotBatchConfirmView {
  settlement_name: string
  building: Named
  lots: LotBatchLot[] | null
  count: number
  cost_money: number
  materials: MaterialLine[] | null
  build_time_seconds: number
}

export interface LotBatchLot {
  x: number
  y: number
}

export interface LotBuyView {
  village: string
  settlement_id: string
  x: number
  y: number
  price: number
  cash: number
  treasury: number
}

export interface LotCell {
  x: number
  y: number
  state: string
  own: boolean
  fits: boolean
}

export interface LotConfirmView {
  settlement_name: string
  building: Named
  x: number
  y: number
  rotated: boolean
  cost_money: number
  materials: MaterialLine[] | null
  build_time_seconds: number
  auto_roads: number
}

export interface LotGridView {
  settlement_name: string
  building: Named
  can_rotate: boolean
  rotated: boolean
  grid_lots: number
  rows: (LotCell[] | null)[] | null
  multi: boolean
  line: string
  from: LotBatchLot
  win_x: number
  win_y: number
}

export interface MarketCheckoutView {
  item: Named
  qty: number
  price: number
  reserve: number
  payment: PaymentChoice
  nonce: string
}

export interface MarketRefusalView {
  kind: string
  item: Named
  count: number
}

export interface MarketView {
  city_code: string
  city: string
  books: BookSummary[] | null
  yours: Named[] | null
  at_market: boolean
  way: Way | null
}

export interface MaterialBought {
  item: Named
  qty: number
  total: number
}

export interface MaterialBuyView {
  village: string
  item: Named
  qty: number
  unit: number
  total: number
  treasury: number
  free: number
}

export interface MaterialLine {
  component: Named
  quantity: number
}

export interface MaterialMarketLine {
  item: Named
  price: number
}

export interface MaterialStockLine {
  item: Named
  qty: number
}

export interface MaterialsView {
  village: string
  treasury: number
  stock: MaterialStockLine[] | null
  used: number
  capacity: number
  market: MaterialMarketLine[] | null
  can_buy: boolean
  presets: number[] | null
  bought: MaterialBought | null
}

export interface MineLot {
  x: number
  y: number
  building: string
  state: string
  finish_at: string | null
  left_seconds: number
}

export interface MineView {
  village: string
  settlement_id: string
  cash: number
  lots: MineLot[] | null
  home: Named | null
  can_rest: boolean
  rest_wait_seconds: number
  assessed: number
  tax_per_period: number
  tax_bps: number
  debt: number
  debt_periods: number
  notice: string
}

export interface MyAuctionsView {
  auctions: AuctionLine[] | null
}

export interface MyOrdersView {
  orders: OrderLine[] | null
}

export interface Named {
  code: string
  name: string
}

export interface NeedBuilding {
  code: string
  role: string
  tier: number
}

export interface OpenOrderLine {
  no: number
  company: Named
  side: string
  qty: number
  filled: number
  price: number
}

export interface OrderCancelledView {
  item: Named
  side: string
  no: number
  left: number
  refund: number
}

export interface OrderLine {
  no: number
  item: Named
  side: string
  qty: number
  filled: number
  price: number
  status: string
  city_code: string
  city: string
  expires_at: string | null
}

export interface OrderPlacedView {
  item: Named
  side: string
  no: number
  qty: number
  filled: number
  price: number
  rests: boolean
  spent: number
  got: number
  expires_at: string | null
  method: string
  embargoed: number
}

export interface PayConfirmView {
  payee_name: string
  payee_code: string
  method: string
  amount: number
  fee: number
  total: number
  after: number
  nonce: string
  origin: string
}

export interface PayHelpView {
}

export interface PaySentView {
  payee_name: string
  payee_code: string
  method: string
  amount: number
  fee: number
  held: boolean
}

export interface PayView {
  payee_name: string
  payee_code: string
  together: boolean
  city_code: string
  city: string
  payer_city_code: string
  payer_city: string
  card_fee_bps: number
  cash: number
  bank: number
  cash_options: AmountOption[] | null
  card_options: AmountOption[] | null
  can_cash: boolean
  can_card: boolean
  origin: string
  notice: string
  notice_args: Record<string, unknown> | null
}

export interface PaymentChoice {
  amount: number
  accepted: string[] | null
  usable: string[] | null
  cash: number
  bank: number
}

export interface PaymentDeclinedView {
  amount: number
  cash: number
  bank: number
  accepted: string[] | null
  back_label: string
  back: Ref
}

export interface PledgeLine {
  no: number
  code: string
  type: Named
  city: GovPlace
  value: number
  limit: number
}

export interface PolicyLine {
  no: number
  product: Named
  covers: string
  property: PledgeLine | null
  status: string
  reason: string
  premium: number
  paid: number
  from: string | null
  started: string | null
  claimable: boolean
}

export interface PortfolioView {
  holdings: HoldingLine[] | null
  orders: OpenOrderLine[] | null
  gold: number
  gold_val: number
  savings: number
  value: number
  gain: number
  notice: string
  notice_args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface PriceOption {
  qty: number
  price: number
}

export interface PrivateConfirmView {
  village: string
  building: Named
  x: number
  y: number
  rotated: boolean
  cost_money: number
  permit_fee: number
  materials: PrivateMaterial[] | null
  materials_cost: number
  total: number
  cash: number
  build_time_seconds: number
}

export interface PrivateLine {
  building: Named
  home: boolean
  class: string
  cost_money: number
  permit_fee: number
  materials: PrivateMaterial[] | null
  build_time_seconds: number
  footprint_w: number
  footprint_h: number
  total: number
  affordable: boolean
}

export interface PrivateLotsView {
  village: string
  building: Named
  can_rotate: boolean
  rotated: boolean
  grid_lots: number
  rows: (LotCell[] | null)[] | null
}

export interface PrivateMaterial {
  component: Named
  need: number
  have: number
  buy: number
  buy_cost: number
}

export interface PrivateMenuView {
  village: string
  settlement_id: string
  cash: number
  owned_lots: number
  free_lots: number
  lines: PrivateLine[] | null
}

export interface PromotionCriterionView {
  kind: string
  role: string
  current: number
  required: number
  met: boolean
}

export interface PromotionView {
  village: string
  from: string
  to: string
  criteria: PromotionCriterionView[] | null
  met: boolean
  can_promote: boolean
  office: string
  settlement_id: string
}

export interface Ref {
  command: string
  args: string[] | null
}

export interface ResidenceView {
  leaving: boolean
  village: string
  home: string
  home_code: string
  cooldown_seconds: number
  population: number
  settlement_id: string
}

export interface SavingsView {
  balance: number
  rate_bps: number
  earned: number
  next: number
  bank: number
  deposits: number[] | null
  withdrawals: number[] | null
  next_at: string | null
  notice: string
  notice_args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface SellOffer {
  shop: Named
  place: Named
  price: number
}

export interface SellOffersView {
  item: Named
  ref: string
  offers: SellOffer[] | null
}

export interface SettlementWhoView {
  name: string
  online: WhoLine[] | null
  offline: number
}

export interface ShelfLine {
  item: Named
  price: number
  stock: number
  busy: boolean
  buyback: number
  next_restock: string | null
}

export interface ShopBoughtView {
  shop: Named
  item: Named
  qty: number
  total: number
  tax: number
  method: string
}

export interface ShopCheckoutView {
  shop: Named
  item: Named
  qty: number
  unit: number
  total: number
  tax: number
  tax_bps: number
  stock: number
  payment: PaymentChoice
  nonce: string
}

export interface ShopLine {
  shop: Named
  place: Named
  here: boolean
}

export interface ShopRefusalView {
  kind: string
  shop: Named
  item: Named
  stock: number
  next_restock: string | null
}

export interface ShopSoldView {
  shop: Named
  item: Named
  price: number
  left: number
}

export interface ShopView {
  shop: Named
  place: Named
  here: boolean
  walk_seconds: number
  shelves: ShelfLine[] | null
  tax_bps: number
}

export interface ShopsView {
  city_code: string
  city: string
  shops: ShopLine[] | null
  place: Named | null
}

export interface StandingLine {
  id: string
  building: Named
  lot_x: number
  lot_y: number
}

export interface StockOrderView {
  company: Named
  side: string
  qty: number
  price: number
  reserve: number
  bank: number
  fee_bps: number
  nonce: string
  placed: boolean
  no: number
  filled: number
  spent: number
  got: number
  rests: boolean
  expires_at: string | null
}

export interface StockView {
  company: Named
  type: Named
  city: GovPlace
  listed: boolean
  price: number
  prev: number
  ipo: number
  book: number
  total: number
  bids: BookLevel[] | null
  asks: BookLevel[] | null
  trades: TradeLine[] | null
  holding: number
  locked: number
  cost: number
  owner: boolean
  controller: string
  buys: PriceOption[] | null
  sells: PriceOption[] | null
  last_div: number
  fee_bps: number
  notice: string
  notice_args: Record<string, unknown> | null
  unavailable: Unavailable | null
}

export interface TermsView {
  village: string
  settlement_id: string
  lot_price: number
  lot_price_min: number
  lot_price_max: number
  permit_fee: number
  permit_fee_max: number
  tax_bps: number
  tax_bps_max: number
  lot_presets: number[] | null
  permit_presets: number[] | null
  tax_presets: number[] | null
  default_lot_price: number
  default_permit: number
  default_tax_bps: number
}

export interface TradeLine {
  qty: number
  price: number
  at: string | null
}

export interface Unavailable {
  service: string
  stage: string
  here: string
  requires: NeedBuilding[] | null
  nearest: Named | null
}

export interface VillageMaker {
  building: Named
  built: boolean
}

export interface VillageNeed {
  kind: string
  item: Named
  options: Named[] | null
  have: number
  need: number
  makers: VillageMaker[] | null
  price: number
}

export interface VillageOverviewView {
  name: string
  tier: string
  population: number
  population_cap: number
  food_percent: number
  job_percent: number
  service_percent: number
  happiness_percent: number
  security_percent: number
  literacy_percent: number
  resident: boolean
  settlement_id: string
  treasury: number
  buildings: VillageRoleLine[] | null
  is_head: boolean
  support: VillageSupport | null
  promotion: PromotionView | null
}

export interface VillageRefusalView {
  kind: string
  back: Ref
  remaining_seconds: number
  min: number
  max: number
  lots: BatchLotFailure[] | null
  action: string
  subject: Named
  needs: VillageNeed[] | null
}

export interface VillageRoleLine {
  role: string
  building: Named
  tier: number
}

export interface VillageSupport {
  code: string
  name: string
}

export interface Way {
  place: Named
  walk_seconds: number
}

export interface WhoLine {
  name: string
  activity: string
  place: string
}

export interface WorkShiftLine {
  building: Named
  finish_at: string | null
  left_seconds: number
  wage: number
  produces: MaterialLine[] | null
}

export interface WorkView {
  village: string
  resident: boolean
  places: WorkplaceLine[] | null
  mine: WorkShiftLine | null
  suggest: Named[] | null
  started: boolean
  used: number
  capacity: number
}

export interface WorkplaceLine {
  id: string
  building: Named
  produces: MaterialLine[] | null
  consumes: MaterialLine[] | null
  wage: number
  shift_seconds: number
  workers: number
  busy: number
  ready: boolean
}

/** The screens of the migrated areas: the screen name on the wire, and its view. */
export interface ScreenViews {
  auction_detail: AuctionView
  auction_new: AuctionNewView
  auction_opened: AuctionOpenedView
  auction_refusal: AuctionRefusalView
  auctions: AuctionsView
  bank: BankView
  bid_placed: BidPlacedView
  book: BookView
  budget: BudgetView
  dividend: DividendView
  exchange: ExchangeView
  finance_hub: FinanceHubView
  finance_refusal: FinanceRefusalView
  gold: GoldView
  gold_trade: GoldTradeView
  insurance: InsuranceView
  insure_confirm: InsureConfirmView
  labor_board: LaborBoardView
  labor_mine: LaborMineView
  labor_site: LaborSiteView
  listing: ListingView
  loan_confirm: LoanConfirmView
  loan_detail: LoanDetailView
  loan_offer: LoanOfferView
  market: MarketView
  market_checkout: MarketCheckoutView
  market_refusal: MarketRefusalView
  my_auctions: MyAuctionsView
  my_orders: MyOrdersView
  order_cancelled: OrderCancelledView
  order_placed: OrderPlacedView
  pay: PayView
  pay_confirm: PayConfirmView
  pay_help: PayHelpView
  pay_sent: PaySentView
  payment_declined: PaymentDeclinedView
  portfolio: PortfolioView
  savings: SavingsView
  sell_offers: SellOffersView
  settlement_build_batch_confirm: LotBatchConfirmView
  settlement_build_confirm: LotConfirmView
  settlement_build_lots: LotGridView
  settlement_build_menu: BuildMenuView
  settlement_building_view: BuildingView
  settlement_construction_progress: ConstructionProgressView
  settlement_grid_grow: GridGrowView
  settlement_knowledge_list: KnowledgeListView
  settlement_land: LandView
  settlement_lot_buy_confirm: LotBuyView
  settlement_lot_buy_done: LotBuyView
  settlement_mine: MineView
  settlement_private_confirm: PrivateConfirmView
  settlement_private_lots: PrivateLotsView
  settlement_private_menu: PrivateMenuView
  settlement_terms: TermsView
  settlement_who: SettlementWhoView
  shop_bought: ShopBoughtView
  shop_checkout: ShopCheckoutView
  shop_detail: ShopView
  shop_refusal: ShopRefusalView
  shop_sold: ShopSoldView
  shops: ShopsView
  stock: StockView
  stock_order: StockOrderView
  village_donate_confirm: DonateView
  village_donate_done: DonateView
  village_donate_menu: DonateView
  village_home_call: EmptyView
  village_home_none: EmptyView
  village_materials: MaterialsView
  village_materials_buy_confirm: MaterialBuyView
  village_overview: VillageOverviewView
  village_promote_confirm: PromotionView
  village_promoted: PromotionView
  village_promotion: PromotionView
  village_refusal: VillageRefusalView
  village_residence_confirm: ResidenceView
  village_residence_done: ResidenceView
  village_work: WorkView
  village_work_started: WorkView
}

/** Screens whose response is a refusal: the answer carries an error code instead of ok. */
export const REFUSAL_SCREENS = ['auction_refusal', 'finance_refusal', 'market_refusal', 'shop_refusal', 'village_refusal'] as const
