#!/usr/bin/env python3
"""Generates src/i18n/ui.fa.ts and ui.en.ts from src/i18n/ui.src.txt.
One line per string: key | Persian | English   ('#' starts a comment line).
Both languages come from one line, so they cannot drift apart."""
import re, sys, os
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, 'src/i18n/ui.src.txt')
rows, seen = [], set()
for n, line in enumerate(open(src, encoding='utf-8'), 1):
    line = line.rstrip('\n')
    if not line.strip() or line.lstrip().startswith('#'):
        continue
    parts = [p.strip() for p in line.split(' | ')]
    if len(parts) != 3 or not all(parts):
        sys.exit(f'ui.src.txt:{n}: need "key | fa | en": {line!r}')
    if parts[0] in seen:
        sys.exit(f'ui.src.txt:{n}: duplicate key {parts[0]}')
    seen.add(parts[0]); rows.append(parts)
def q(s): return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"
head = '// GENERATED by scripts/gen-i18n.py from ui.src.txt: do not edit by hand.\n'
fa = head + 'export const uiFa = {\n' + ''.join(f'  {q(k)}: {q(f)},\n' for k, f, e in rows) + '} as const\n\nexport type UiKey = keyof typeof uiFa\n'
en = head + "import type { UiKey } from './ui.fa'\n\nexport const uiEn: Record<UiKey, string> = {\n" + ''.join(f'  {q(k)}: {q(e)},\n' for k, f, e in rows) + '}\n'
open(os.path.join(root, 'src/i18n/ui.fa.ts'), 'w', encoding='utf-8').write(fa)
open(os.path.join(root, 'src/i18n/ui.en.ts'), 'w', encoding='utf-8').write(en)
print(len(rows), 'strings')
